CREATE TABLE oder_signedOrder_updhistory
(
  id INT(11) AUTO_INCREMENT COMMENT '主键ID',
  signedOrderId INT(11) DEFAULT NULL COMMENT '签约单ID',
  roomSalePrice VARCHAR(250) DEFAULT NULL COMMENT '修改价格',
  paymentType	VARCHAR(250) DEFAULT NULL COMMENT '付款方式',
  checkinDate	VARCHAR(250) DEFAULT NULL COMMENT '入住时间',
  rentPeriod	VARCHAR(250) DEFAULT NULL COMMENT '租期',
  remark	VARCHAR(500) DEFAULT NULL COMMENT '备注',
  STATUS TINYINT(1) DEFAULT '1' COMMENT '状态(0无效1有效)',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='签约单修改记录';