DELETE FROM mesg_template WHERE TYPE='sms_renter_mogobao_lakala_success';
DELETE FROM mesg_template WHERE TYPE='sms_renter_mogobao_mogo_success';
DELETE FROM mesg_template WHERE TYPE='sms_CreateMogobaoSaleBillByBill_before3';
DELETE FROM mesg_template WHERE TYPE='sms_CreateMogobaoSaleBillByBill_today';
DELETE FROM mesg_template WHERE TYPE='sms_CreateMogobaoLklBillByBill_before3';
DELETE FROM mesg_template WHERE TYPE='sms_CreateMogobaoLklBillByBill_today';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_validated';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_duedate';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_duedate4';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_duedate5';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_payback_failure';
DELETE FROM mesg_template WHERE TYPE='sms_partner_loan_put_amount';
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_renter_mogobao_lakala_success','[蘑菇宝已通过]您的蘑菇宝已通过审核，请每月交租日前在蘑菇宝关联借记卡中存够租金，按时支付房租。蘑菇租房400-800-4949','0','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_renter_mogobao_mogo_success','[蘑菇宝已通过]您的蘑菇宝已通过审核，请每月交租日前登录蘑菇租房APP支付房租。蘑菇租房400-800-4949','0','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_CreateMogobaoSaleBillByBill_before3','[账单即将逾期]您的${1}-${2}月的租金账单支付期限还剩余3日，请在3日内（${3}之前）登录APP完成支付。蘑菇租房400-800-4949',3,'1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_CreateMogobaoSaleBillByBill_today','[账单已到期]您的${1}-${2}月租金账单今日已到期，请务必要在今日（${3}）24点之前完成支付，否则将被退房。蘑菇租房400-800-4949',3,'1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_CreateMogobaoLklBillByBill_before3','[账单未付提醒]您的${1}-${2}月的租金账单支付日为${3}，请您确保支付日当天17:00前蘑菇宝关联的借记卡中存有全额租金，按时支付房租。蘑菇租房400-800-4949',3,'1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_CreateMogobaoLklBillByBill_today','[账单到期]你${1}-${2}月的租金账单今日已到期，请务必在今日17:00前确保蘑菇宝关联的借记卡中存有全额租金，否则将被退房。蘑菇租房400-800-4949',2,'1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_validated','[租金宝]恭喜您的租金宝审核已通过，接下来请耐心等待放款。蘑菇租房400-800-4949','0','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_duedate','[租金宝逾期]您的租金宝已经逾期${1}天，请通知租客${2}（${3}）及时支付本月房租，否则您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949','3','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_duedate4','[租金宝逾期]您的租金宝已经逾期${1}天，请通知租客${2}（${3}）及时支付本月房租，否则明天您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949','3','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_duedate5','[租金宝已终止]租客${1}（${2}）蘑菇宝逾期未支付租金，已经被强制退房，请及时处理。对应的租金宝已经中止，请确保个人帐户余额留有足够金额${3}元，买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949','3','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_payback_failure','[租金宝买回失败]租客${1}对应的租金宝买回失败，您的帐户提现功能已被冻结，请及时充值${2}元，买回对应租金宝。蘑菇租房400-800-4949','2','1');
INSERT INTO mesg_template ( `type`, `content`, `paramCount`, `status`) VALUES('sms_partner_loan_put_amount','[租金宝放款]您的租金宝已经成功放款，放款金额${1}元，对应房源${2}，请登录蘑菇伙伴APP查看详情。蘑菇租房400-800-4949','2','1');
