
/* 消息模板*/
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103001,'mesg_category','mesg_category_his','消息类别','消息类别名称','categoryName','categoryId',0,1,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103001,'mesg_category','mesg_category_his','消息类别','消息类别描述','cateDesc','categoryId',0,2,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103002,'mesg_category','mesg_category_his','消息类别','消息类别名称','categoryName','categoryId',0,1,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103002,'mesg_category','mesg_category_his','消息类别','消息类别描述','cateDesc','categoryId',0,2,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103004,'mesg_templet','mesg_templet_his','消息模板','模板名称','templetName','templetId',0,1,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103004,'mesg_templet','mesg_templet_his','消息模板','模板描述','templetDesc','templetId',0,2,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103005,'mesg_templet','mesg_templet_his','消息模板','模板名称','templetName','templetId',0,1,'');
INSERT INTO comm_business_record_mapping(busiType,tableName,tableNameHis,tablelabel,tableColumnlabel,tableColumnName,checkUnicolumn,isCommwrite,sort,decodeSql) VALUES(160103005,'mesg_templet','mesg_templet_his','消息模板','模板描述','templetDesc','templetId',0,2,'');
