use mogoroomdb;

/* 消息管理模块菜单初始化 */
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '1003225', '消息模板管理', '', '25', '1', SELECT id FROM `perm_functioninfo` WHERE fname ='系统管理', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '2307010', '消息类别管理', 'mesgTemp/mesgCategoryList', '10', '2', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板管理', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3307205', '添加', 'mesgTemp/addMesgCategory', '5', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息类别管理', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3307210', '编辑', 'mesgTemp/editMesgCategory', '10', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息类别管理', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3307215', '删除', 'mesgTemp/delMesgCategory', '15', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息类别管理', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '2307020', '消息修改记录', 'mesgTemp/editTempLog', '20', '2', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板管理', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3307405', '消息业务类型查询', 'mesgTemp/selectBizType', '5', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息修改记录', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '2307025', '消息发送记录', 'mesgTemp/sendRecord', '25', '2', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板管理', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '2307030', '消息模板列表', 'mesgTemp/mesgTempList', '30', '2',SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板管理', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308305', '启用/禁用消息子模板', 'mesgTemp/enableOrDisableSubTemp', '5', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308310', '启用禁用消息主模板', 'mesgTemp/enableOrDisableTemp', '10', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308315', '删除消息模板', 'mesgTemp/delTemp', '15', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308320', '添加消息模板', 'mesgTemp/addTemp', '20', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308325', '添加/编辑模板-保存消息模板', 'mesgTemp/saveTemp', '25', '3',SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308330', '添加/编辑模板-验证模板是否已存在', 'mesgTemp/checkMesgTempTitle', '30', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '0', null, null, null, '1', '0', null, null, null, null, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES ( '3308335', '编辑消息模板', 'mesgTemp/editTemp', '35', '3', SELECT id FROM `perm_functioninfo` WHERE fname ='消息模板列表', '1', null, null, null, '0', '0', null, null, null, null, '1', '2');


