use mogoroomdb;
select @id:=id from perm_functioninfo where fname = '房源推广';
select @seq:=(max(seq)+1) from perm_functioninfo where functionpId=@id;
select @fcode:= CONCAT('2',lpad(@id,4,0),2 ) from perm_functioninfo where fname = '房源推广';
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode, '房源推广列表', 'joint/toJointFlats', @seq, '2', @id, '1', NULL, NULL, NULL, '0', '1', NULL, NULL, NULL, NULL, '1', '2');

select @id2:=id from perm_functioninfo where fname = '房源推广列表';
select @seq2:=(max(seq)+1) from perm_functioninfo where functionpId=@id;
select @fcode2:= CONCAT('3',lpad(@id2,4,0),1 ) from perm_functioninfo where fname = '房源推广列表';
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '查找推广模板', 'joint/findJointTemplate', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '更新推广模板', 'joint/updateJointTemplate', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '批量上架', 'joint/batchOnlineRoom', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '批量下架', 'joint/batchOfflineRoom', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '下架', 'joint/offlineRoom', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '上架', 'joint/onlineRoom', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '更新房源模板', 'joint/updateRoomTemplate', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '房源上架列表', 'joint/toUnjointFlats', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '推广列表', 'joint/toJointFlats', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) VALUES (@fcode2:=@fcode2+1, '查找具体模板', 'joint/findRoomTemplateById', @seq2, '3', @id2, '0', NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '1', '2');
