/*添加职业房东操作日志内容*/
use mogoroomdb;

BEGIN;
/*业务日志类型 */
INSERT INTO `comm_busitype` (`busiType`, `busiName`, `status`, `sort`, `parentId`, `level`, `isLeaf`) VALUES ('160101010', '职业房东信息', '1', '1', '160101', '3', '1');

/* 房东扩展信息 */
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '信用代码', 'creditCode', 'userLandlordInfoId', '0', '1', 'tid', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '法定代表人', 'legalRepresentative', 'userLandlordInfoId', '0', '1', 'tid', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '房东签约人', 'salesmanId', 'userLandlordInfoId', '0', '1', 'tid', 'select `name`  from user_employee where id  = %s');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '签约单数', 'signCount', 'userLandlordInfoId', '0', '1', 'tid', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '签约时间', 'contractDate', 'userLandlordInfoId', '0', '1', 'tid', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '合同甲方', 'legalPerson', 'userLandlordInfoId', '0', '1', 'tid', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '蘑菇认证', 'isVerified', 'userLandlordInfoId', '0', '1', 'tid', 'SELECT CASE %s WHEN 0 THEN \'否\'  ELSE \'是\' END  isVerified');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord_info', 'user_landlord_info_his', '房东扩展信息', '签约城市', 'applyCityId', 'userLandlordInfoId', '0', '1', 'tid', 'SELECT `name` FROM `city` where id = %s');

/* 房东信息 */
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '国籍', 'nationality', 'landlordId', '0', '1', 'id', 'SELECT chName FROM `city_country`  where id = %s');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '备注', 'remark', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '紧急联系人电话', 'emergencyPhone', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '房东服务人', 'customerMgr', 'landlordId', '0', '1', 'id', 'select `name`  from user_employee where id  = %s');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '紧急联系人', 'emergency', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '签约来源', 'landlordSource', 'landlordId', '0', '1', 'id', 'SELECT `value` FROM `comm_dictionary` where `groupName` =\'landlordSource\' AND keyPro =%s');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '品牌名称', 'brandName', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '证件号', 'identityId', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '证件类型', 'card_type', 'landlordId', '0', '1', 'id', 'SELECT `value`  FROM comm_dictionary WHERE groupname=\'credential\' AND code = \'%s\'');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '电子邮箱', 'email', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '分机号', 'phoneExt', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '微信号', 'weixin', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '手机号', 'contactPhone', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '房东性别', 'sex', 'landlordId', '0', '1', 'id', 'SELECT CASE %s WHEN 0 THEN \'女\'  ELSE \'男\' END  sex');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '伙伴帐号', 'phone', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '职业房东', 'name', 'landlordId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_landlord', 'user_landlord_his', '房东信息', '图片', 'photo', 'landlordId', '0', '1', 'id', NULL);



/* 房东绑卡信息 */
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '银行', 'bankName', 'bankcardId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '账户类型', 'isCorp', 'bankcardId', '0', '1', 'id', 'SELECT CASE %s WHEN 0 THEN \'个人\'  ELSE \'公司\' END  isCorp');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '银行卡号', 'bankCardNumber', 'bankcardId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '开户名', 'realName', 'bankcardId', '0', '1', 'id', NULL);
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '银行类型', 'card_type', 'bankcardId', '0', '1', 'id', 'SELECT CASE \'%s\' WHEN \'DEBIT\' THEN \'借记卡\' WHEN \'CREDIT\' THEN \'信用卡\'  ELSE \'其他\' END  card_type');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '省份', 'province', 'bankcardId', '0', '1', 'id', '');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '城市', 'city', 'bankcardId', '0', '1', 'id', '');
INSERT INTO `comm_business_record_mapping` ( `busiType`, `tableName`, `tableNameHis`, `tableLabel`, `tableColumnLabel`, `tableColumnName`, `checkUniColumn`, `isCommWrite`, `sort`, `tableKey`, `decodeSql`) VALUES ( '160101010', 'user_bankCard', 'user_bankcard_his', '房东绑卡', '支行', 'bank_branch', 'bankcardId', '0', '1', 'id', NULL);

COMMIT;