/* Database name `mogoroomdb` */

use mogoroomdb;

/*初始化获取CA数据*/
INSERT INTO user_caidentification (
	user_caidentification.userId,
	user_caidentification.userType,
	user_caidentification.caChannel,
	user_caidentification.phone,
	user_caidentification.identityId,
	user_caidentification.`name`,
	user_caidentification.applyCityId,
	user_caidentification.acctType,
	user_caidentification.address,
	user_caidentification.account,
	user_caidentification.`password`,
	user_caidentification.uid,
	user_caidentification.`status`,
	user_caidentification.remark,
	user_caidentification.createTime,
	user_caidentification.createBy,
	user_caidentification.createByType,
	user_caidentification.updateTime,
	user_caidentification.updateBy,
	user_caidentification.updateByType,
	user_caidentification.valid
)(
	SELECT
		user_landlord_caidentification.landlordId,
		0,
		10,
		user_landlord_caidentification.phone,
		user_landlord_caidentification.identityId,
		user_landlord_caidentification.`name`,
		user_landlord_caidentification.applyCityId,
		user_landlord_caidentification.acctType,
		user_landlord_caidentification.address,
		user_landlord_caidentification.account,
		user_landlord_caidentification.`password`,
		user_landlord_caidentification.uid,
		user_landlord_caidentification.`status`,
		user_landlord_caidentification.remark,
		user_landlord_caidentification.createTime,
		user_landlord_caidentification.createBy,
		user_landlord_caidentification.createByType,
		user_landlord_caidentification.updateTime,
		user_landlord_caidentification.updateBy,
		user_landlord_caidentification.updateByType,
		user_landlord_caidentification.valid
	FROM
		user_landlord_caidentification
);

/*初始化实名认证表*/
INSERT INTO user_identity (
	user_identity.userId,
	user_identity.userType,
	user_identity.identityId,
	user_identity.`name`,
	user_identity.`status`,
	user_identity.remark,
	user_identity.createTime,
	user_identity.createBy,
	user_identity.createByType,
	user_identity.updateTime,
	user_identity.updateBy,
	user_identity.updateByType,
	user_identity.valid
)(
	SELECT
		user_landlord_identity.landlordId,
		0,
		user_landlord_identity.identityId,
		user_landlord_identity.`name`,
		user_landlord_identity.`status`,
		user_landlord_identity.remark,
		user_landlord_identity.createTime,
		user_landlord_identity.createBy,
		user_landlord_identity.createByType,
		user_landlord_identity.updateTime,
		user_landlord_identity.updateBy,
		user_landlord_identity.updateByType,
		user_landlord_identity.valid
	FROM
		user_landlord_identity
);