use mogoroomdb;


insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('1','289',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('2','289',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('3','289',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('4','131',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('5','131',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('6','131',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('7','340',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('8','340',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('9','340',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('10','289',NULL,'51','纸质合同模板','zzht001','/var/lib/docker/contract/template/zzht.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('11','131',NULL,'51','纸质合同模板','zzht001','/var/lib/docker/contract/template/zzht.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('12','340',NULL,'51','纸质合同模板','zzht001','/var/lib/docker/contract/template/zzht.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('13','289',NULL,'52','转客合同模板','zkht001','/var/lib/docker/contract/template/zk.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('14','131',NULL,'52','转客合同模板','zkht001','/var/lib/docker/contract/template/zk.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`id`, `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('15','340',NULL,'52','转客合同模板','zkht001','/var/lib/docker/contract/template/zk.vm','1','2016-04-08 03:59:33','1','1',NULL,NULL,NULL,'1');
