/** 支付完成后新增字段，用于统计是否使用行用卡支付字段。并在字典表中新增映射枚举 **/
USE mogoroomdb;
ALTER TABLE `bill_paylog_weixin`  ADD COLUMN `isCredit` TINYINT(4) COMMENT '是否使用信用卡' ;
ALTER TABLE `bill_paylog_zhifubao` ADD COLUMN `isCredit` TINYINT(4) COMMENT '是否使用信用卡' ;
ALTER TABLE `bill_paylog_zhifubao` ADD COLUMN `out_channel_type` VARCHAR(50) COMMENT '交易类型(参考字典表：outChannelType)' ;

INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-0','outChannelType',0,'BALANCE','余额',1,NULL,'余额');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-1','outChannelType',1,'CREDIT_PAY','信用支付支付方式类型',1,NULL,'信用支付支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-2','outChannelType',2,'CASH','现金支付方式类型',1,NULL,'现金支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-3','outChannelType',3,'CONSUMER_CARD','消费卡支付方式类型',1,NULL,'消费卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-4','outChannelType',4,'COUPON','红包支付方式类型',1,NULL,'红包支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-5','outChannelType',5,'VOUCHER','购物券支付方式类型',1,NULL,'购物券支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-6','outChannelType',6,'POINT','积分支付方式类型',1,NULL,'积分支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-7','outChannelType',7,'MDISCOUNT','商户优惠券支付方式',1,NULL,'商户优惠券支付方式');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-8','outChannelType',8,'COUPON_DC_MCOUPON_DEFAULT','商户红包',1,NULL,'商户红包');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-9','outChannelType',9,'WANG_HUI_E','网汇E支付方式类型',1,NULL,'网汇E支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-10','outChannelType',10,'PREPAID_CARD','预存卡支付方式类型',1,NULL,'预存卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-11','outChannelType',11,'INTERNATIONAL_CREDIT_CARD','国际卡类型',1,NULL,'国际卡类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-12','outChannelType',12,'PREPAY','预付卡支付方式类型',1,NULL,'预付卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-13','outChannelType',13,'RT_DISCOUNT','实时优惠支付方式类型',1,NULL,'实时优惠支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-14','outChannelType',14,'CARTOON','借记卡卡通支付方式类型',1,NULL,'借记卡卡通支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-15','outChannelType',15,'SC_DEBIT_CARTOON','结算中心借记卡卡通支付方式类型',1,NULL,'结算中心借记卡卡通支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-16','outChannelType',16,'B2C_EBANK','借记卡B2C网银支付方式类型',1,NULL,'借记卡B2C网银支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-17','outChannelType',17,'B2B_EBANK','B2B网银支付方式类型',1,NULL,'B2B网银支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-18','outChannelType',18,'WANGDIAN_DEBIT_CARD','网点借记卡刷卡支付方式类型',1,NULL,'网点借记卡刷卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-19','outChannelType',19,'DEBIT_EXPRESS','借记卡快捷支付方式类型',1,NULL,'借记卡快捷支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-20','outChannelType',20,'CREDIT_CARTOON','普通信用卡卡通支付方式类型',1,NULL,'普通信用卡卡通支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-21','outChannelType',21,'BIGAMOUNT_CREDIT_CARTOON','大额信用卡卡通支付方式类型',1,NULL,'大额信用卡卡通支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-22','outChannelType',22,'VISA','VISA网银支付方式类型',1,NULL,'VISA网银支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-23','outChannelType',23,'CREDIT_CARD_EBANK','信用卡网关支付方式类型',1,NULL,'信用卡网关支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-24','outChannelType',24,'MOTO_CREDIT_CARD','moto信用卡支付方式类型',1,NULL,'moto信用卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-25','outChannelType',25,'OPTIMIZED_MOTO','信用卡快捷支付类型',1,NULL,'信用卡快捷支付类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-26','outChannelType',26,'CREDIT_EXPRESS_INSTALLMENT','信用卡快捷分期支付类型',1,NULL,'信用卡快捷分期支付类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-27','outChannelType',27,'WANGDIAN_CREDIT_CARD','网点信用卡刷卡支付方式类型',1,NULL,'网点信用卡刷卡支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-28','outChannelType',28,'INTERNATIONAL_CREDIT_CARD_VISA','VISA支付方式类型',1,NULL,'VISA支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-29','outChannelType',29,'INTERNATIONAL_CREDIT_CARD_MASTER','MASTER支付方式类型',1,NULL,'MASTER支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-30','outChannelType',30,'INTERNATIONAL_CREDIT_CARD_JCB','JCB支付方式类型3',1,NULL,'JCB支付方式类型3');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-31','outChannelType',31,'MIXED_B2C_EBANK','混合卡B2C网银支付方式类型',1,NULL,'混合卡B2C网银支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-32','outChannelType',32,'PCREDIT_CC_PCREDIT_INSTALLMENT','花呗分期支付方式类型',1,NULL,'花呗分期支付方式类型');
INSERT INTO `comm_dictionary`  (CODE,groupName,sort,keyPro,VALUE,STATUS,fcode,enValue) VALUES ('outchannel-33','outChannelType',33,'PCREDIT_PAY','花呗支付方式类型',1,NULL,'花呗支付方式类型');
