USE mogoroomdb;
 
/*2016-09-07 前的合同按照之前的合同走*/ 
update cntr_contract_templet t set t.endTime = '2016-09-07 03:05:21' where t.templetCode ='zzht001' and t.rentType ='51';
update cntr_contract_templet t set t.endTime = '2016-09-07 03:05:21' where t.templetCode ='zkht001' and t.rentType ='52';
/*2016-09-07 后的合同走新模版*/ 
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('289', NULL, '51', '纸质合同模板', 'zzht001', '/var/lib/docker/contract/template/v2/zzht.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('131', NULL, '51', '纸质合同模板', 'zzht001', '/var/lib/docker/contract/template/v2/zzht.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('340', NULL, '51', '纸质合同模板', 'zzht001', '/var/lib/docker/contract/template/v2/zzht.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('289', NULL, '52', '转客合同模板', 'zkht001', '/var/lib/docker/contract/template/v2/zk.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('131', NULL, '52', '转客合同模板', 'zkht001', '/var/lib/docker/contract/template/v2/zk.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');
INSERT INTO `cntr_contract_templet` ( `cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`, `beginTime`, `endTime`) VALUES ('340', NULL, '52', '转客合同模板', 'zkht001', '/var/lib/docker/contract/template/v2/zk.vm', '1', now(), '1', '1', NULL, NULL, NULL, '1', '2016-09-07 03:05:21', '2020-12-31 23:59:59');


INSERT INTO  `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`, `enValue`) VALUES ('renewTip-title', 'renewTip', '0', NULL, '温馨提示', '1', NULL, 'title');
INSERT INTO  `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`, `enValue`) VALUES ('renewTip-content', 'renewTip', '1', NULL, '该账单为续租账单，为了保证您的权益，请先去“查看租约”确认续租合同后，再来支付续租账单。', '1', NULL, 'content');
INSERT INTO  `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`, `enValue`) VALUES ('renewTip-clean', 'renewTip', '2', NULL, '{"name":"取消","onClick":0,"link":null,"fontStyle":null}', '1', NULL, 'button');
INSERT INTO  `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`, `enValue`) VALUES ('renewTip-confirm', 'renewTip', '3', NULL, '{"name":"查看租约","onClick":1,"link":null,"fontStyle":"#007aff"}', '1', NULL, 'button');
