-- MySQL Script generated by MySQL Workbench
-- 11/17/15 17:09:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema acct
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `acct_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_account` ;

CREATE TABLE IF NOT EXISTS `acct_account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acctId` INT(11) NOT NULL COMMENT '帐务系统账号',
  `wjIdentity` VARCHAR(32) NOT NULL COMMENT '维金帐号',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `userId` INT(11) NOT NULL COMMENT '业务系统帐号唯一标识',
  `userType` TINYINT(4) NOT NULL COMMENT '业务用户类型  1 租客 2 房东   groupName=userType',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18947
DEFAULT CHARACTER SET = utf8
COMMENT = '账号表';


-- -----------------------------------------------------
-- Table `acct_bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_bill` ;

CREATE TABLE IF NOT EXISTS `acct_bill` (
  `billId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单编号',
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '账单总金额',
  `unpayAmount` DECIMAL(10,2) NOT NULL COMMENT '未结清费用',
  `acctId` INT(11) NOT NULL COMMENT '付款账号',
  `toAcctId` INT(11) NULL DEFAULT NULL COMMENT '收款账号',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(1024) NOT NULL COMMENT '备注',
  `origBillId` INT(32) NULL DEFAULT NULL COMMENT '关联账单编号',
  `deadline` DATE NULL DEFAULT NULL,
  `paidPenalty` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '已支付滞纳金额',
  PRIMARY KEY (`billId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账单表';


-- -----------------------------------------------------
-- Table `acct_bill_chghistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_bill_chghistory` ;

CREATE TABLE IF NOT EXISTS `acct_bill_chghistory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `billId` INT(11) NOT NULL COMMENT '账单id。参考账单表。',
  `oldAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单变更前金额',
  `oldDeadline` DATE NULL DEFAULT NULL COMMENT '账单变更前截止日期',
  `newAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单变更后金额',
  `newDeadline` DATE NULL DEFAULT NULL COMMENT '账单变更后截止日期',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL DEFAULT NULL COMMENT '创建人id',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型。参考字段表useType。',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账单变更履历表';


-- -----------------------------------------------------
-- Table `acct_bill_tmp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_bill_tmp` ;

CREATE TABLE IF NOT EXISTS `acct_bill_tmp` (
  `billId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单编号',
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '账单总金额',
  `unpayAmount` DECIMAL(10,2) NOT NULL COMMENT '未结清费用',
  `acctId` INT(11) NOT NULL COMMENT '付款账号',
  `toAcctId` INT(11) NULL DEFAULT NULL COMMENT '收款账号',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(1024) NOT NULL COMMENT '备注',
  `origBillId` INT(32) NULL DEFAULT NULL COMMENT '关联账单编号',
  `deadline` DATE NULL DEFAULT NULL,
  `orderId` VARCHAR(32) NULL DEFAULT NULL COMMENT '订单号\n\n            ',
  `orderType` INT(6) NULL DEFAULT NULL COMMENT '订单类型\n\n            ',
  `fromTblName` VARCHAR(64) NULL DEFAULT NULL COMMENT '订单号从业务系统哪个表迁移过来的',
  `memo` VARCHAR(128) NULL DEFAULT NULL COMMENT '账单迁移备注',
  `paidPenalty` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '已支付滞纳金额',
  PRIMARY KEY (`billId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '数据迁移用临时账单表';


-- -----------------------------------------------------
-- Table `acct_billdtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_billdtl` ;

CREATE TABLE IF NOT EXISTS `acct_billdtl` (
  `billDtlId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单明细编号',
  `billId` INT(32) NOT NULL COMMENT '账单编号',
  `billDtlType` INT(11) NOT NULL COMMENT '账单明细类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额',
  PRIMARY KEY (`billDtlId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账单详情';


-- -----------------------------------------------------
-- Table `acct_billdtltype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_billdtltype` ;

CREATE TABLE IF NOT EXISTS `acct_billdtltype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `billDtlType` INT(11) NOT NULL COMMENT '账单明细类型',
  `billDtlName` VARCHAR(64) NOT NULL COMMENT '账单明细名称',
  `status` TINYINT(4) NOT NULL COMMENT '0无效1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8
COMMENT = '账单类型';


-- -----------------------------------------------------
-- Table `acct_billtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_billtype` ;

CREATE TABLE IF NOT EXISTS `acct_billtype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `billName` VARCHAR(64) NOT NULL COMMENT '账单名称',
  `status` TINYINT(4) NOT NULL COMMENT '0无效1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  `penaltyRate` INT(4) NULL DEFAULT NULL COMMENT '滞纳金适用费率。单位：万分之一',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COMMENT = '账单类型';


-- -----------------------------------------------------
-- Table `acct_billtypetofundtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_billtypetofundtype` ;

CREATE TABLE IF NOT EXISTS `acct_billtypetofundtype` (
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `fromFundType` INT(32) NOT NULL COMMENT '扣款资金类型',
  `toFundType` INT(32) NOT NULL COMMENT '收款资金类型',
  PRIMARY KEY (`billType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账单类型与资金抵扣方式';


-- -----------------------------------------------------
-- Table `acct_busibilldtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_busibilldtl` ;

CREATE TABLE IF NOT EXISTS `acct_busibilldtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `doneCode` INT(11) NOT NULL COMMENT '流水主表ID',
  `billId` INT(11) NOT NULL COMMENT '账单号',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额，账单费用增加为正',
  `beforeAmount` DECIMAL(10,2) NOT NULL COMMENT '支付前金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '流水账单表';


-- -----------------------------------------------------
-- Table `acct_busifeedtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_busifeedtl` ;

CREATE TABLE IF NOT EXISTS `acct_busifeedtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `doneCode` INT(32) NOT NULL COMMENT '流水主表ID',
  `acctId` INT(11) NOT NULL COMMENT '账号id',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额，入款为正',
  `fundChannel` INT(2) NOT NULL COMMENT '渠道',
  `bankCode` VARCHAR(16) NOT NULL COMMENT '银行编号',
  `bankCard` VARCHAR(32) NOT NULL COMMENT '银行',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9301
DEFAULT CHARACTER SET = utf8
COMMENT = '资金来源';


-- -----------------------------------------------------
-- Table `acct_busifunddtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_busifunddtl` ;

CREATE TABLE IF NOT EXISTS `acct_busifunddtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `doneCode` INT(32) NOT NULL COMMENT '业务流水id',
  `acctId` INT(32) NOT NULL COMMENT '账号id',
  `fundType` INT(11) NOT NULL COMMENT '资金类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '变化金额，余额增加为正',
  `beforeAmount` DECIMAL(10,2) NOT NULL COMMENT '变化前金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19342
DEFAULT CHARACTER SET = utf8
COMMENT = '资金';


-- -----------------------------------------------------
-- Table `acct_busirec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_busirec` ;

CREATE TABLE IF NOT EXISTS `acct_busirec` (
  `doneCode` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `tradelogid` INT(11) NOT NULL COMMENT '支付行为外键',
  `busiType` INT(11) NOT NULL COMMENT '业务类型',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `reRecId` INT(11) NULL DEFAULT NULL COMMENT '退款关联ID',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `createBy` INT(11) NOT NULL COMMENT '操作人',
  `createByType` TINYINT(4) NOT NULL COMMENT '操作人类型',
  `channel` TINYINT(4) NOT NULL COMMENT '交易渠道',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`doneCode`))
ENGINE = InnoDB
AUTO_INCREMENT = 16991
DEFAULT CHARACTER SET = utf8
COMMENT = '账务流水表';


-- -----------------------------------------------------
-- Table `acct_busitype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_busitype` ;

CREATE TABLE IF NOT EXISTS `acct_busitype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `busiType` INT(11) NOT NULL COMMENT '业务代码',
  `busiName` VARCHAR(64) NOT NULL COMMENT '业务名称',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '业务类型';


-- -----------------------------------------------------
-- Table `acct_check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_check` ;

CREATE TABLE IF NOT EXISTS `acct_check` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '告警结果描述',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '修改之后是否已经审核',
  `checkResult` TINYINT(4) NULL DEFAULT NULL COMMENT '审核结果',
  `fundChannel` TINYINT(4) NULL DEFAULT NULL COMMENT '付款渠道',
  `checkDate` DATE NULL DEFAULT NULL COMMENT '对账日',
  `checkType` TINYINT(4) NULL DEFAULT NULL COMMENT '对账类型 余额 资金 业务',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8
COMMENT = '检查结果';


-- -----------------------------------------------------
-- Table `acct_checkacctfunddetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checkacctfunddetail` ;

CREATE TABLE IF NOT EXISTS `acct_checkacctfunddetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `accountId` INT(11) NULL DEFAULT NULL COMMENT '个人帐户号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  `errorType` TINYINT(4) NULL DEFAULT NULL COMMENT '余额错误类型',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31621
DEFAULT CHARACTER SET = utf8
COMMENT = '个人帐户对账结果详情';


-- -----------------------------------------------------
-- Table `acct_checkbillfunddetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checkbillfunddetail` ;

CREATE TABLE IF NOT EXISTS `acct_checkbillfunddetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `billId` INT(11) NULL DEFAULT NULL COMMENT '账单号',
  `waterBillId` INT(11) NULL DEFAULT NULL COMMENT '流水表中的billId',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(32) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '流水帐务，账单对账结果详情';


-- -----------------------------------------------------
-- Table `acct_checkbilltradedetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checkbilltradedetail` ;

CREATE TABLE IF NOT EXISTS `acct_checkbilltradedetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `tradeLogId` INT(11) NULL DEFAULT NULL COMMENT '支付行为id',
  `billTradeLogId` INT(11) NULL DEFAULT NULL COMMENT '帐务中的tradeLogId',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6647
DEFAULT CHARACTER SET = utf8
COMMENT = '个人帐户对账结果详情';


-- -----------------------------------------------------
-- Table `acct_checkbizdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checkbizdetail` ;

CREATE TABLE IF NOT EXISTS `acct_checkbizdetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '对账结果id  ,acct_check.id',
  `origBillNum` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务系统账单号',
  `billId` INT(11) NULL DEFAULT NULL COMMENT '账单号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '业务系统与帐务系统对账结果详情';


-- -----------------------------------------------------
-- Table `acct_checktradealipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checktradealipay` ;

CREATE TABLE IF NOT EXISTS `acct_checktradealipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务流水号',
  `fcDoneCode` VARCHAR(64) NOT NULL COMMENT '第三方流水号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acct_checktradedetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checktradedetail` ;

CREATE TABLE IF NOT EXISTS `acct_checktradedetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '对账结果id  ,acct_check.id',
  `tradeNo` VARCHAR(32) NULL DEFAULT NULL COMMENT '交易编号',
  `oppoTradeNo` VARCHAR(32) NULL DEFAULT NULL COMMENT '支付商付款流水号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `fundChannel` INT(11) NULL DEFAULT NULL COMMENT '付款渠道',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '错误描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COMMENT = '检查交易结果详情';


-- -----------------------------------------------------
-- Table `acct_checktradeweixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_checktradeweixin` ;

CREATE TABLE IF NOT EXISTS `acct_checktradeweixin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务流水号',
  `fcDoneCode` VARCHAR(64) NOT NULL COMMENT '第三方流水号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acct_fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_fund` ;

CREATE TABLE IF NOT EXISTS `acct_fund` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acctId` INT(11) NOT NULL COMMENT '账号',
  `fundType` INT(11) NOT NULL COMMENT '资金类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额',
  `frozen` DECIMAL(10,2) NOT NULL COMMENT '冻结金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账号余额表';


-- -----------------------------------------------------
-- Table `acct_fundtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_fundtype` ;

CREATE TABLE IF NOT EXISTS `acct_fundtype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `fundCode` VARCHAR(64) NOT NULL COMMENT '唯一编码',
  `fundName` INT(11) NOT NULL COMMENT '名称',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '资金类型';


-- -----------------------------------------------------
-- Table `acct_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_password` ;

CREATE TABLE IF NOT EXISTS `acct_password` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `acctId` INT(11) NOT NULL COMMENT '会员编号',
  `passType` TINYINT(4) NOT NULL COMMENT '密码类型',
  `password` VARCHAR(64) NOT NULL COMMENT '支付密码',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `createBy` INT(11) NOT NULL COMMENT '创建人ID',
  `createByType` INT(11) NOT NULL COMMENT '创建人类型',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人ID',
  `updateByType` INT(11) NULL DEFAULT NULL COMMENT '更新人类型',
  `status` TINYINT(4) NOT NULL COMMENT '状态，是否有效',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '支付密码';


-- -----------------------------------------------------
-- Table `acct_passwordlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_passwordlog` ;

CREATE TABLE IF NOT EXISTS `acct_passwordlog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '日志id',
  `acctId` INT(11) NOT NULL COMMENT '会员编号',
  `busiType` INT(11) NOT NULL COMMENT '访问类型',
  `accessResult` VARCHAR(32) NOT NULL COMMENT '访问结果',
  `accessTime` DATETIME NOT NULL COMMENT '访问时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '日志';


-- -----------------------------------------------------
-- Table `acct_refund_alipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_refund_alipay` ;

CREATE TABLE IF NOT EXISTS `acct_refund_alipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `biz_orderid` VARCHAR(30) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '业务类型',
  `notify_time` DATETIME NOT NULL COMMENT ' 格式为 yyyy-MM-dd HH:mm:ss ',
  `notify_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '通知的类型   业务类型',
  `notify_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '通知校验的ID ',
  `sign_type` VARCHAR(10) NULL DEFAULT NULL COMMENT '固定取值为 RSA   ',
  `sign` VARCHAR(1024) NULL DEFAULT NULL COMMENT '签名',
  `out_trade_no` VARCHAR(64) NOT NULL COMMENT '对应商户网站的订单系统中的 唯一订单号，非支付宝交易号。                                                                                                                           \n\n                                                                                                                                需保证在商户网站中的唯一性。 是请求时对应的参数，原样返 回',
  `subject` VARCHAR(128) NULL DEFAULT NULL COMMENT '商品的标题/交易标题/订单标题 /订单关键字等。 它在支付宝的交易明细中排在 第一列，对于财务对账尤为重 要。是请求时对应的参数，原样 通知回来。  ',
  `payment_type` VARCHAR(4) NULL DEFAULT NULL COMMENT '支付类型。默认值为：1（商品 购买                   ',
  `trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '该交易在支付宝系统中的交易 流水号。 最短 16 位，最长 64 位',
  `trade_status` VARCHAR(20) NULL DEFAULT NULL COMMENT '交易状态',
  `seller_id` VARCHAR(30) NULL DEFAULT NULL COMMENT '卖家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `seller_email` VARCHAR(100) NULL DEFAULT NULL COMMENT '卖家支付宝账号，可以是 email 和手机号码。',
  `buyer_id` VARCHAR(30) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号',
  `buyer_email` VARCHAR(100) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字。',
  `total_fee` DOUBLE NULL DEFAULT NULL COMMENT '该笔订单的总金额。 请求时对应的参数，原样通知回 来。 ',
  `quantity` DOUBLE NULL DEFAULT NULL COMMENT '购买数量，',
  `price` DOUBLE NULL DEFAULT NULL COMMENT 'price 等于 total_fee',
  `body` VARCHAR(512) NULL DEFAULT NULL COMMENT '该笔订单的备注',
  `gmt_create` DATETIME NULL DEFAULT NULL COMMENT '该笔交易创建的时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `gmt_payment` DATETIME NULL DEFAULT NULL COMMENT '该笔交易的买家付款时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `is_total_fee_adjust` VARCHAR(1) NULL DEFAULT NULL COMMENT '该交易是否调整过价格 ',
  `use_coupon` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在交易过程中使用了红包',
  `discount` VARCHAR(10) NULL DEFAULT NULL COMMENT ' 支付宝系统会把 discount 的值 加到交易金额上，如果有折扣， 本参数为负数，单位为元 ',
  `refund_status` VARCHAR(20) NULL DEFAULT NULL COMMENT '取值范围请参见“11.4  退款状 态”',
  `gmt_refund` DATETIME NULL DEFAULT NULL COMMENT '卖家退款的时间，退款通知时会 发送。 格式为 yyyy-MM-dd HH:mm:ss',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '支付宝退款记录';


-- -----------------------------------------------------
-- Table `acct_refund_weixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_refund_weixin` ;

CREATE TABLE IF NOT EXISTS `acct_refund_weixin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `appid` VARCHAR(32) NOT NULL COMMENT '公众账号ID',
  `mch_id` VARCHAR(32) NOT NULL COMMENT '商户号',
  `device_info` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
  `nonce_str` VARCHAR(32) NOT NULL COMMENT '随机字符串',
  `sign` VARCHAR(32) NOT NULL COMMENT '签名',
  `transaction_id` VARCHAR(28) NOT NULL COMMENT '微信订单号',
  `out_trade_no` VARCHAR(32) NOT NULL COMMENT '商户订单号',
  `out_refund_no` VARCHAR(32) NOT NULL COMMENT '商户退款单号',
  `refund_id` VARCHAR(28) NOT NULL COMMENT '微信退款单号',
  `refund_channel` VARCHAR(16) NOT NULL COMMENT '退款渠道',
  `refund_fee` INT(11) NOT NULL COMMENT '退款金额',
  `total_fee` INT(11) NOT NULL COMMENT '订单总金额',
  `fee_type` VARCHAR(8) NULL DEFAULT NULL COMMENT '订单金额货币种类',
  `cash_fee` INT(11) NOT NULL COMMENT '现金支付金额',
  `cash_refund_fee` INT(11) NULL DEFAULT NULL COMMENT '现金退款金额',
  `coupon_refund_fee` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠退款金额',
  `coupon_refund_count` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠使用数量',
  `coupon_refund_id` VARCHAR(20) NULL DEFAULT NULL COMMENT '代金券或立减优惠ID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '微信退款记录';


-- -----------------------------------------------------
-- Table `acct_speciallist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_speciallist` ;

CREATE TABLE IF NOT EXISTS `acct_speciallist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `acctId` INT(11) NULL DEFAULT NULL COMMENT '账号id',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL DEFAULT NULL COMMENT '创建人',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型',
  `updateTime` DATE NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `udpateByType` TINYINT(4) NULL DEFAULT NULL COMMENT '更新人类型',
  `blackType` TINYINT(4) NULL DEFAULT NULL COMMENT '黑名单类型',
  `status` TINYINT(4) NULL DEFAULT NULL COMMENT '状态，0无效，1有效',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '账号黑白灰名单';


-- -----------------------------------------------------
-- Table `acct_thridrefund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_thridrefund` ;

CREATE TABLE IF NOT EXISTS `acct_thridrefund` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `billId` INT(11) NOT NULL COMMENT '账单编号',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '退款金额',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `refundChannel` INT(11) NOT NULL COMMENT '退款渠道',
  `status` INT(11) NOT NULL COMMENT '状态 1有效，0无效',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '第三方扣款计划表';


-- -----------------------------------------------------
-- Table `acct_tradelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_tradelog` ;

CREATE TABLE IF NOT EXISTS `acct_tradelog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务侧流水号',
  `busiType` INT(11) NOT NULL COMMENT '业务类型 详见业务类型表',
  `channel` TINYINT(4) NOT NULL COMMENT '操作渠道  租客APP：0 ， 房东APP：1，房东PC：2 ，bs系统：3',
  `fundChannel` INT(4) NULL DEFAULT NULL COMMENT '资金渠道 支付宝：1,，微信：2，维金：3，余额：4',
  `fcDoneCode` VARCHAR(64) NULL DEFAULT NULL COMMENT '第三方平台交易ID',
  `useFund` TINYINT(4) NOT NULL COMMENT '是否使用资金 1:是 0：不是',
  `billId` INT(32) NULL DEFAULT NULL COMMENT '账单ID  ',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `createByType` INT(11) NOT NULL COMMENT '创建人类型 租客：0 ，房东：1，MOGO员工：2',
  `createBy` INT(11) NOT NULL COMMENT '创建人',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `status` INT(2) NOT NULL COMMENT '状态  原始状态：1，支付完成 ：2',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '交易行为日志';


-- -----------------------------------------------------
-- Table `acct_tradelog_alipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_tradelog_alipay` ;

CREATE TABLE IF NOT EXISTS `acct_tradelog_alipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `biz_orderid` INT(11) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务类型',
  `notify_time` DATETIME NULL DEFAULT NULL COMMENT '通知的发送时间。 格式为 yyyy-MM-dd HH:mm:ss',
  `notify_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '通知的类型',
  `notify_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '通知校验的ID',
  `sign_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '固定取值为 RSA',
  `sign` VARCHAR(1024) NULL DEFAULT NULL COMMENT '签名',
  `out_trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '对应商户网站的订单系统中的 唯一订单号，非支付宝交易号。 需保证在商户网站中的唯一性。 是请求时对应的参数，原样返 回。',
  `subject` VARCHAR(128) NULL DEFAULT NULL COMMENT '商品的标题/交易标题/订单标题 /订单关键字等。 它在支付宝的交易明细中排在 第一列，对于财务对账尤为重 要。是请求时对应的参数，原样 通知回来。',
  `payment_type` VARCHAR(4) NULL DEFAULT NULL COMMENT '支付类型。默认值为：1（商品 购买）',
  `trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '该交易在支付宝系统中的交易 流水号。 最短 16 位，最长 64 位。',
  `trade_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '交易状态，取值范围请参见 “11.3 交易状态”',
  `seller_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '卖家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `seller_email` VARCHAR(128) NULL DEFAULT NULL COMMENT '卖家支付宝账号，可以是 email 和手机号码。',
  `buyer_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `buyer_email` VARCHAR(128) NULL DEFAULT NULL COMMENT '买家支付宝账号，可以是 Email 或手机号码',
  `total_fee` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '该笔订单的总金额。 请求时对应的参数，原样通知回 来。',
  `quantity` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '购买数量，固定取值为 1（请求 时使用的是 total_fee）。',
  `price` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'price 等于 total_fee（请求时使 用的是 total_fee）',
  `body` VARCHAR(512) NULL DEFAULT NULL COMMENT '该笔订单的备注、描述、明细等。 对应请求时的 body 参数，原样 通知回来。',
  `gmt_create` DATETIME NULL DEFAULT NULL COMMENT '该笔交易创建的时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `gmt_payment` DATETIME NULL DEFAULT NULL COMMENT '该笔交易的买家付款时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `is_total_fee_adjust` VARCHAR(1) NULL DEFAULT NULL COMMENT '该交易是否调整过价格',
  `use_coupon` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在交易过程中使用了红包',
  `discount` VARCHAR(16) NULL DEFAULT NULL COMMENT '支付宝系统会把 discount 的值 加到交易金额上，如果有折扣， 本参数为负数，单位为元',
  `refund_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '取值范围请参见“11.4 退款状 态”',
  `gmt_refund` DATETIME NULL DEFAULT NULL COMMENT '卖家退款的时间，退款通知时会 发送。 格式为 yyyy-MM-dd HH:mm:ss。',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '支付宝交易日志';


-- -----------------------------------------------------
-- Table `acct_tradelog_weixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_tradelog_weixin` ;

CREATE TABLE IF NOT EXISTS `acct_tradelog_weixin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `biz_orderid` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务类型',
  `return_code` VARCHAR(16) NULL DEFAULT NULL COMMENT 'SUCCESS/FAIL 此字段是通信标识，非交易标识，交易是否成功需要查看result_code来判断',
  `return_msg` VARCHAR(128) NULL DEFAULT NULL COMMENT '返回信息，如非空，为错误原因 签名失败 参数格式校验错误',
  `appid` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信分配的公众账号ID（企业号corpid即为此appId）',
  `mch_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付分配的商户号',
  `device_info` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付分配的终端设备号，',
  `nonce_str` VARCHAR(32) NULL DEFAULT NULL COMMENT '随机字符串，不长于32位',
  `sign` VARCHAR(32) NULL DEFAULT NULL COMMENT '签名',
  `result_code` VARCHAR(16) NULL DEFAULT NULL COMMENT 'SUCCESS/FAIL',
  `err_code` VARCHAR(32) NULL DEFAULT NULL COMMENT '错误返回的信息描述',
  `err_code_des` VARCHAR(128) NULL DEFAULT NULL COMMENT '错误返回的信息描述',
  `openid` VARCHAR(128) NULL DEFAULT NULL COMMENT '用户在商户appid下的唯一标识',
  `is_subscribe` VARCHAR(1) NULL DEFAULT NULL COMMENT '用户是否关注公众账号，Y-关注，N-未关注，仅在公众账号类型支付有效',
  `trade_type` VARCHAR(16) NULL DEFAULT NULL COMMENT 'JSAPI、NATIVE、APP',
  `bank_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '银行类型',
  `total_fee` INT(11) NULL DEFAULT NULL COMMENT '订单总金额，单位为分',
  `fee_type` VARCHAR(8) NULL DEFAULT NULL COMMENT '货币类型，符合ISO4217标准的三位字母代码，默认人民币：CNY，',
  `cash_fee` INT(11) NULL DEFAULT NULL COMMENT '现金支付金额订单现金支付金额',
  `cash_fee_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '货币类型，符合ISO4217标准的三位字母代码，默认人民币：CNY',
  `coupon_fee` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠金额<=订单总金额，订单总金额-代金券或立减优惠金额=现金支付金额',
  `coupon_count` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠使用数量',
  `coupon_id_$n` VARCHAR(32) NULL DEFAULT NULL COMMENT '代金券或立减优惠ID,$n为下标，从0开始编号',
  `coupon_fee_$n` INT(11) NULL DEFAULT NULL COMMENT '单个代金券或立减优惠支付金额,$n为下标，从0开始编号',
  `transaction_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付订单号',
  `out_trade_no` VARCHAR(32) NULL DEFAULT NULL COMMENT '商户系统的订单号，与请求一致。',
  `attach` VARCHAR(128) NULL DEFAULT NULL COMMENT '商家数据包，原样返回',
  `time_end` VARCHAR(16) NULL DEFAULT NULL COMMENT '支付完成时间，格式为yyyyMMddHHmmss，如2009年12月25日9点10分10秒表示为20091225091010。',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '微信交易日志';


-- -----------------------------------------------------
-- Table `bill_cbf_operlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bill_cbf_operlog` ;

CREATE TABLE IF NOT EXISTS `bill_cbf_operlog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fundChannel` INT(11) NOT NULL COMMENT '支付提供商类型 3001 微信 2001 支付宝',
  `operType` VARCHAR(32) NOT NULL COMMENT '操作类型 1支付 2退款',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `businessId` VARCHAR(100) NOT NULL COMMENT '业务编号',
  `businessType` VARCHAR(100) NOT NULL COMMENT '业务类型',
  `origOutertradeNo` VARCHAR(100) NULL DEFAULT NULL COMMENT '冻结编号',
  `moneyAmount` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '金额',
  `operatorId` INT(11) NULL DEFAULT NULL COMMENT '操作人员',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '回调失败操作日志表';


-- -----------------------------------------------------
-- Table `acct_billdtl_chghistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct_billdtl_chghistory` ;

CREATE TABLE IF NOT EXISTS `acct_billdtl_chghistory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `billId` INT(11) NOT NULL COMMENT '账单id。参考账单表。',
  `billDtlId` INT(11) NOT NULL COMMENT '账单详细id。参考账单详细表。',
  `oldAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单详细变更前金额',
  `oldBillDtlType` INT(11) NULL COMMENT '账单详细变更前类型',
  `newAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单详细变更后金额',
  `newBillDtlType` INT(11) NULL DEFAULT NULL COMMENT '账单详细变更后类型',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL DEFAULT NULL COMMENT '创建人id',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型。参考字段表useType。',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账单变更履历表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
