/*  新增蘑菇金融下面的蘑菇月付的拓展审核列表、蘑菇月付服务申请列表的菜单，删掉原有的蘑菇月付资质申请列表下的所有菜单*/
USE mogoroomdb;

BEGIN;

/* 拓展审核列表*/
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(2,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付'),4,0)),'07')),'拓展审核列表','loanMonthlyPayApply/landlordMonthlyPayExpandAuditList','7','2',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付'),'1',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');


INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'01')),'查询拓展审核列表','loanMonthlyPayApply/landlordMonthlyPayExpandAuditList','1','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'02')),'打开房东信息采集','loanMonthlyPayApply/turnToInfoCollectionPage','2','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'03')),'检查是否存在申请资料','loanMonthlyPayApply/checkIsExistsMpayApply','3','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'04')),'保存房东信息采集','loanMonthlyPayApply/saveInfoCollection','4','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'05')),'查询信息采集详情页面','loanMonthlyPayApply/turnToInfoCollectionDetailPage','5','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'06')),'是否能查看详情','loanMonthlyPayApply/checkIsCanOpenApplyInfoDetailBusi','6','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'07')),'申请资料详情','loanMonthlyPayApply/turnToApplyInfoDetailBusi','7','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'08')),'拓展一审','loanMonthlyPayApply/busiOneApproveOperate','8','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'09')),'校验能否打开一审页面','loanMonthlyPayApply/checkIsCanOpenApplyInfoWhenBusiOneApprove','9','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'10')),'打开拓展审核页面','loanMonthlyPayApply/turnToApplyInfoWhenBusiOneApprove','10','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'11')),'拓展经理审核','loanMonthlyPayApply/busiTwoApproveOperate','11','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'12')),'校验能否打开二审页面','loanMonthlyPayApply/checkIsCanOpenApplyInfoWhenBusiTwoApprove','12','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),4,0)),'13')),'打开拓展经理审核页面','loanMonthlyPayApply/turnToApplyInfoWhenBusiTwoApprove','13','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '拓展审核列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');


/* 蘑菇月付服务申请列表*/
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(2,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付'),4,0)),'08')),'蘑菇月付服务申请列表','loanMonthlyPayApply/monthlyApplyCreditApproverList','8','2',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付'),'1',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');


INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'01')),'查询蘑菇月付服务申请列表','loanMonthlyPayApply/monthlyApplyCreditApproverList','1','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'02')),'资质生效','loanMonthlyPayApply/effectLandlordCredit','2','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'03')),'蘑菇月付服务申请列表导出','loanMonthlyPayApply/exportMonthlyApplyCreditApproverList','3','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'04')),'申请列表查看申请详情','loanMonthlyPayApply/turnToApplyInfoDetailCredit','4','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'05')),'打开信审一审页面','loanMonthlyPayApply/turnToApplyInfoWhenCreditOneApprove','5','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'06')),'打开信审二审页面','loanMonthlyPayApply/turnToApplyInfoWhenCreditTwoApprove','6','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'07')),'信审一审','loanMonthlyPayApply/creditOneApproveOperate','7','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'08')),'信审二审','loanMonthlyPayApply/creditTwoApproveOperate','8','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'09')),'信审一审审核通过弹框','loanMonthlyPayApply/findCreditDetailBeforeCreditOneApprovePass','9','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'10')),'打开审核拒绝弹框','loanMonthlyPayApply/allEffectApplyRejectReason','10','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'11')),'查询拒绝原因','loanMonthlyPayApply/allEffectRejectReasonList','11','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'12')),'保存拒绝原因','loanMonthlyPayApply/resetEffectApplyRejectReason','12','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'13')),'打开上传和编辑合同页面','loanMonthlyPayApply/turnToUploadContractPage','13','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'14')),'保存签约合同','loanMonthlyPayApply/saveUploadContractOperate','14','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');

INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),4,0)),'15')),'新增房东月付资质','loanMonthlyPayApply/addNewLandlordCreditApply','15','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '蘑菇月付服务申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');



/*新增蘑菇宝资质*/
INSERT INTO `perm_functioninfo` (`fcode`, `fname`, `furl`, `seq`, `functionLevel`, `functionpId`, `functionisMenu`, `functionVcode`, `functionParam`, `functionFaclass`, `isAjax`, `functionType`, `createdBy`, `createdTime`, `updatedBy`, `updatedTime`, `status`, `channel`) 
VALUES((SELECT CONCAT(3,(SELECT LPAD((SELECT id FROM perm_functioninfo e WHERE e.fname = '租金宝申请列表'),4,0)),'29')),'新增蘑菇宝资质','rentVerify/addNewLandlordCredit','29','3',(SELECT id FROM perm_functioninfo e WHERE e.fname = '租金宝申请列表'),'0',NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,'1','2');


/* 删掉原有的蘑菇月付资质申请列表，用拓展审核列表、蘑菇月付服务申请列表代替 */
DELETE FROM perm_functioninfo   WHERE functionpId IN ( SELECT subquery.pid FROM (SELECT subpf.id AS pid FROM perm_functioninfo subpf WHERE subpf.fname ='蘑菇月付资质申请列表') subquery );

DELETE FROM perm_functioninfo WHERE fname ='蘑菇月付资质申请列表';

COMMIT;