
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-1','period','1','1','首期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-2','period','2','2','二期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-3','period','3','3','三期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-4','period','4','4','四期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-5','period','5','5','五期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-6','period','6','6','六期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-7','period','7','7','七期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-8','period','8','8','八期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-9','period','9','9','九期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-10','period','10','10','十期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-11','period','11','11','十一期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('period-12','period','12','12','十二期','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordContractStatus-1','loanLandlordContractStatus','1','1','审核中','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordContractStatus-2','loanLandlordContractStatus','2','2','审核通过','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordContractStatus-3','loanLandlordContractStatus','3','3','审核失败','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordMgmtStatus-1','loanLandlordMgmtStatus','1','1','放款中','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordMgmtStatus-2','loanLandlordMgmtStatus','2','2','放款失败','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordMgmtStatus-3','loanLandlordMgmtStatus','3','3','放款中止','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordMgmtStatus-4','loanLandlordMgmtStatus','4','4','放款完成','1',NULL);
INSERT INTO `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) VALUES ('loanLandlordMgmtStatus-5', 'loanLandlordMgmtStatus', '5', '5', '款项结清', '1', NULL);

insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordPayStatus-1','loanLandlordPayStatus','1','1','待放款','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordPayStatus-2','loanLandlordPayStatus','2','2','放款失败','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordPayStatus-3','loanLandlordPayStatus','3','3','放款中止','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordPayStatus-4','loanLandlordPayStatus','4','4','放款完成','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordRepayStatus-1','loanLandlordRepayStatus','1','1','待还款','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordRepayStatus-2','loanLandlordRepayStatus','2','2','已中止','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordRepayStatus-3','loanLandlordRepayStatus','3','3','已还款','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordBuyBackType-1','loanLandlordBuyBackType','1','1','正常退租','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordBuyBackType-2','loanLandlordBuyBackType','2','2','逾期退租','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordBuyBackStatus-1','loanLandlordBuyBackStatus','1','1','买回中','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('loanLandlordBuyBackStatus-2','loanLandlordBuyBackStatus','2','2','买回完成','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('mogobaoBuyBackStatus-1','mogobaoBuyBackStatus','1','0','蘑菇宝待买回','1',NULL);
insert into `comm_dictionary` (`code`, `groupName`, `sort`, `keyPro`, `value`, `status`, `fcode`) values('mogobaoBuyBackStatus-2','mogobaoBuyBackStatus','2','1','蘑菇宝已买回','1',NULL);
