/* Database name `mogoroomdb` ，合同模板初始化 */
use mogoroomdb;

delete from `cntr_contract_templet`;

insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('289',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('289',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('289',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('131',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('131',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('131',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('340',NULL,'3','整租模板','zhengzu001','/var/lib/docker/contract/template/zz.vm','1','2016-01-04 11:15:56','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('340',NULL,'2','合租模板','hezu001','/var/lib/docker/contract/template/hz.vm','1','2015-12-30 20:26:39','1','1',NULL,NULL,NULL,'1');
insert into `cntr_contract_templet` (`cityId`, `landlordId`, `rentType`, `templetName`, `templetCode`, `templetPath`, `status`, `createTime`, `createBy`, `createByType`, `updateTime`, `updateBy`, `updateByType`, `lang`) values('340',NULL,'1','自营合同模板','ziying001','/var/lib/docker/contract/template/zy.vm','1','2015-12-22 14:51:37','1','1',NULL,NULL,NULL,'1');
