use mogoroomdb;

INSERT INTO comm_dictionary (CODE, groupName, sort, keyPro, VALUE, enValue)
VALUES
("landlordName", "contractTemplet", 1, "1", "房东/甲方姓名", "landlordName"),
("renterRealName", "contractTemplet", 2, "2", "承租人/乙方姓名", "renterRealName"),
("landlordAddress", "contractTemplet", 3, "3", "房东（甲方）地址", "landlordAddress"),
("renterAddress", "contractTemplet", 4, "4", "租客（乙方）地址", "renterAddress"),
("contractRemark", "contractTemplet", 5, "5", "合同补充条款", "contractRemark"),
("realName", "contractTemplet", 6, "6", "租客姓名", "realName"),
("sex", "contractTemplet", 7, "7", "租客性别", "sex"),
("cellphone", "contractTemplet", 8, "8", "租客手机号", "cellphone"),
("cardType", "contractTemplet", 9, "9", "租客证件类型", "cardType"),
("cardId", "contractTemplet", 10, "10", "租客证件号", "cardId"),
("idPhoto", "contractTemplet", 11, "11", "租客证件照片", "idPhoto"),
("rentPayType", "contractTemplet", 12, "12", "租金付款方式", "rentPayType"),
("depositMoney", "contractTemplet", 13, "13", "押金总额（含其他押金）", "depositMoney"),
("depositListStr", "contractTemplet", 14, "14", "押金明细（含其他押金）", "depositListStr"),
("depositMoneyRMB", "contractTemplet", 15, "15", "押金总额（含其他押金）大写", "depositMoneyRMB"),
("monthRentMoney", "contractTemplet", 16, "16", "每月房租金额", "monthRentMoney"),
("monthRentMoneyRMB", "contractTemplet", 17, "17", "每月房租金额大写", "monthRentMoneyRMB"),
("firstOtherMoney", "contractTemplet", 18, "18", "首期一次性费用总额", "firstOtherMoney"),
("firstOtherMoneyListStr", "contractTemplet", 19, "19", "首期一次性费用明细", "firstOtherMoneyListStr"),
("firstOtherMoneyRMB", "contractTemplet", 20, "20", "首期一次性费用总额大写", "firstOtherMoneyRMB"),
("monthOtherMoney", "contractTemplet", 21, "21", "每月周期性费用总额", "monthOtherMoney"),
("monthOtherMoneyListStr", "contractTemplet", 22, "22", "每月周期性费用明细", "monthOtherMoneyListStr"),
("monthOtherMoneyRMB", "contractTemplet", 23, "23", "每月周期性费用总额大写", "monthOtherMoneyRMB"),
("payPreDays", "contractTemplet", 24, "24", "提前交租天数", "payPreDays"),
("landlordFeesList", "contractTemplet", 25, "25", "租金包含费用类目", "landlordFeesList"),
("periodNumber", "contractTemplet", 26, "26", "期数", "periodNumber"),
("startAndEndTime", "contractTemplet", 27, "27", "租约起止日期", "startAndEndTime"),
("leaseTerm", "contractTemplet", 28, "28", "租约期长", "leaseTerm"),
("startTime", "contractTemplet", 29, "29", "租约开始日期", "startTime"),
("roomInfo", "contractTemplet", 30, "30", "房源地址", "roomInfo"),
("roomFurnitureList", "contractTemplet", 32, "32", "房间家具清单", "roomFurnitureList"),
("flatsFurnitureList", "contractTemplet", 32, "32", "公共家具清单", "flatsFurnitureList"),
("payTypeText", "contractTemplet", 33, "33", "支付方式", "payTypeText"),
("area", "contractTemplet", 34, "34", "房源面积", "area");