/* use mogoroomdb 模板脚本初始化 */

use mogoroomdb;

INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid) VALUES(1, 'sms_alert_landlordInitPwd', '房东初始化密码', '房东初始化密码', 1, 2, STR_TO_DATE('2015-12-05 16:29:15','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(2, 'sms_flats_verify_landlord', '房源审核通过', '房源审核通过', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(3, 'sms_flats_unVerify_landlord', '房源审核未通过', '房源审核未通过', 1, 2, STR_TO_DATE('2015-12-05 17:31:24','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(4, 'sms_flatsType_verify_landlord', '房型审核结果通知', '房型审核结果通知', 1, 2, STR_TO_DATE('2015-12-07 12:20:23','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(5, 'sms_flatsType_unVerify_landlord', '房型审核结果通知', '房型审核结果通知', 1, 2, STR_TO_DATE('2015-12-07 12:20:23','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(6, 'sms_flats_verifyHint_landlord', '房源审核通知', '房源审核通知', 1, 2, STR_TO_DATE('2015-12-07 12:30:13','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(7, 'sms_picture_unVerify_landlord', '照片审核未通过', '照片审核未通过', 1, 2, STR_TO_DATE('2015-12-07 12:12:44','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(8, 'sms_repairAdd_landlord', '报修通知', '报修通知', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(9, 'sms_partner_comming_hostacct', '支付租金通知', '支付租金通知', 1, 2, STR_TO_DATE('2015-12-05 17:49:31','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(10, 'sms_partner_hostacct_duedate', '租金过期通知', '租金过期通知', 1, 2, STR_TO_DATE('2015-12-05 18:02:32','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(11, 'sms_landlord_bookOrderSuccess', '新预订单审核', '新预订单审核', 1, 2, STR_TO_DATE('2015-12-05 18:08:01','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 2);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(12, 'sms_complainAdd_landlord', '投诉房东', '投诉房东', 1, 2, STR_TO_DATE('2015-12-07 12:04:11','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(13, 'sms_partner_loan_payback_failure', '租金宝买回失败', '租金宝买回失败', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(14, 'sms_partner_loan_put_amount', '租金宝放款', '租金宝放款', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(15, 'sms_partner_loan_validated', '租金宝审核通过', '租金宝审核通过', 1, 2, STR_TO_DATE('2015-12-07 13:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(16, 'sms_landlord_guanWangYuyueSuccessNotify', '租客预约看房', '租客预约看房', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 1);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(17, 'sms_landlord_payDeposit', '房东账户充值', '房东账户充值', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(18, 'sms_renter_exept', '租客支付账单通知（分散式）', '租客支付账单通知（分散式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 10);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(19, 'sms_renter_exept_foucs', '租客支付账单通知（集中式）', '租客支付账单通知（集中式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 10);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(20, 'sms_landlord_mogobao_lakala_success', '蘑菇宝已通过', '蘑菇宝已通过', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 3);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(21, 'sms_renter_saleContractConvert_success', '补录租约（分散式）', '补录租约（分散式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 9);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(22, 'sms_renter_saleContractConvert_foucs_success', '补录租约（集中式）', '补录租约（集中式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 9);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(23, 'sms_renter_saleContractConvert_failure', '补录租约（集中式）', '补录租约（集中式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 8);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(24, 'sms_renter_saleContractConvert_foucs_failure', '补录租约（集中式）', '补录租约（集中式）', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 8);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(25, 'sms_partner_loan_duedate', '租客逾期小于4天', '租客逾期小于4天', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(26, 'sms_partner_loan_duedate4', '租客逾期等于4天', '租客逾期等于4天', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(27, 'sms_partner_loan_duedate5', '租客逾期5天以上包含5天', '租客逾期5天以上包含5天', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(28, 'sms_landlord_mogobao_end_failure', '蘑菇宝终审不通过', '蘑菇宝终审不通过', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(29, 'sms_renter_mogobao_end_failure', '蘑菇宝终审不通过', '蘑菇宝终审不通过', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(30, 'sms_landlord_mogobao_lakala_one_failure', '蘑菇宝首次申请不通过', '蘑菇宝首次申请不通过', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(31, 'sms_landlord_mogobao_lakala_two_failure', '蘑菇宝审批不通过', '蘑菇宝审批不通过', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(32, 'sms_landlord_repayPlan', '租客成功支付', '租客成功支付', 1, 2, STR_TO_DATE('2015-12-05 17:09:07','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(33, 'sms_partner_loan_payback_success', '租金宝买回成功', '租金宝买回成功', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(34, 'sms_complainSolve_landlord', '投诉已解决', '投诉已解决', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(35, 'sms_complainUndo_landlord', '投诉已撤销', '投诉已撤销', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(36, 'sms_outhome_landlord', '退房消息', '退房消息', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 7);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(37, 'sms_rental_applyfor_submit', '租金宝申请已提交', '租金宝申请已提交', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(38, 'sms_repairsSolve_landlord', '报修已解决', '报修已解决', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(39, 'sms_repairsUndo_landlord', '报修已撤销', '报修已撤销', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (id, templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES(40, 'sms_signing_wait_audit', '签约审核通知', '签约审核通知', 1, 2, STR_TO_DATE('2015-12-07 12:35:55','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 3);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('1', '预约', '预约', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 1);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('2', '预订', '预订', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 2);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('3', '签约', '签约', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 3);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('4', '售后', '售后', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 4);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('5', '资金', '资金', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 5);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('6', '其他', '其他', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 6);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('7', '退房', '退房', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 7);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('8', '补录租约意见', '补录租约意见', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 8);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('9', '补录租约同意', '补录租约同意', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 9);
INSERT INTO mesg_templet (templetCode, templetName, templetDesc, status, createBy, createTime, createByType, updateBy, updateTime, updateByType, valid, businessType) VALUES('10', '豁免操作', '豁免操作', 1, 2, STR_TO_DATE('2015-12-07 12:26:20','%Y-%m-%d %H:%i:%s'), 3, NULL, NULL, NULL, 1, 10);


-- 脚本在业务组建模板后运行
SELECT @templetId:= id FROM mesg_templet WHERE  templetCode = '1';
SELECT @mesg_recordStartId:= 1;

INSERT INTO mesg_record (id,templetId,sendTime,receiveBy,receiveByType,createTime)
SELECT @mesg_recordStartId+id,msgType+@templetId-1,sendTime,sendTo,0,NOW() FROM mesg_to_partner WHERE sendTime IS NOT NULL;

INSERT INTO mesg_push_record (recordId,pushTitle,pushContent,regId,deviceType,willsendTime,sendStatus,sendNum,isRead,reason,createTime,lastSendTime,valid)
SELECT @mesg_recordStartId+id,tilte,content,'dump',0,sendTime,1,1,`status`,'老数据迁移',NOW(),NOW(),1 FROM mesg_to_partner WHERE sendTime IS NOT NULL;

UPDATE mesg_push_record SET isRead = 1 WHERE isRead = 2



