/* use mogoroomdb 模板脚本初始化 */

use mogoroomdb;

INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(1, 1, '房东初始化密码', '${landlordName}先生/女士您好，您的“蘑菇伙伴”账号已经创建成功，系统为您自动生成的6位登录密码为${password}。为了您的账户安全，请用本手机号登录“蘑菇伙伴”并及时修改密码。', 1, 1, '', NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(2, 1, '公寓审核', '您好，您提交的房源${roomInfo}审核已通过并上线，若有租客请求，请及时处理。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(2, 3, '公寓审核', '您好，您提交的房源${roomInfo}审核已通过并上线，若有租客请求，请及时处理。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(3, 1, '公寓审核', '您好，您提交的房源${roomInfo}审核未通过，请及时修正重新提交审核。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(3, 3, '公寓审核', '您好，您提交的房源${roomInfo}审核未通过，请及时修正重新提交审核。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(4, 1, '公寓审核', '您好，您提交的房型{roomType}下属房间共{roomNum}，审核已通过并上线，若有租客请求，请及时处理。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(4, 3, '公寓审核', '您好，您提交的房型{roomType}下属房间共{roomNum}，审核已通过并上线，若有租客请求，请及时处理。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(5, 1, '公寓审核', '您好，您提交的房型{roomType}下属房间共{roomNum}，审核未通过，请及时修正重新提交审核。', 1, 1, NULL, NULL);																			    
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(5, 3, '公寓审核', '您好，您提交的房型{roomType}下属房间共{roomNum}，审核未通过，请及时修正重新提交审核。', 1, 1, NULL, NULL);																			    
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(6, 1, '公寓审核', '您的房源已经发布成功！蘑菇租房会对您所提交的房源信息进行审核，若您所提交的房源信息不真实、不准确，蘑菇租房核实后会下线该房源并一律按“假房源”进行处罚！', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(6, 3, '公寓审核', '您的房源已经发布成功！蘑菇租房会对您所提交的房源信息进行审核，若您所提交的房源信息不真实、不准确，蘑菇租房核实后会下线该房源并一律按“假房源”进行处罚！', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(7, 1, '图片审核未通过', '您好，您房源${roomInfo}的照片审核未通过(原因：${verifyIdea})，请及时修正重新提交审核。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(7, 3, '图片审核未通过', '您好，您房源${roomInfo}的照片审核未通过(原因：${verifyIdea})，请及时修正重新提交审核。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(8, 1, '${roomInfo}有一条报修', '${roomInfo}有一条报修!', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(8, 3, '${roomInfo}有一条报修', '${roomInfo}有一条报修!', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(9, 1, '业主账单前7天', '您需要在7日内向${flatCommunity}的业主支付租金，支付完成后请登录蘑菇伙伴确认付款。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(9, 3, '业主账单前7天', '您需要在7日内向${flatCommunity}的业主支付租金，支付完成后请登录蘑菇伙伴确认付款。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(10, 1, '业主欠款', '${flatCommunity}的业主租金已过期，请及时补交，若已支付请登录蘑菇伙伴确认付款。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(10, 3, '业主欠款', '${flatCommunity}的业主租金已过期，请及时补交，若已支付请登录蘑菇伙伴确认付款。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(11, 1, '预定单', '你有一笔新的预定单，请在60分钟内完成审核！', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(11, 3, '预定单', '你有一笔新的预定单，请在60分钟内完成审核！', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(12, 1, '${roomInfo}有一条投诉', '${roomInfo}有一条投诉!', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(12, 3, '${roomInfo}有一条投诉', '${roomInfo}有一条投诉!', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(13, 1, '租金宝买回失败，租客逾期5天', '[租金宝买回失败]租客${renterName}对应的租金宝买回失败，您的帐户提现功能已被冻结，请及时充值${countMoney}元，买回对应租金宝。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(13, 3, '租金宝买回失败，租客逾期5天', '[租金宝买回失败]租客${renterName}对应的租金宝买回失败，您的帐户提现功能已被冻结，请及时充值${countMoney}元，买回对应租金宝。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(14, 1, '租金宝放款', '[租金宝放款]您的租金宝已经成功放款，对应房源${roomInfo}，租客${renterName}, 租金总额${loanAmount}元，保证金${depositAmount}元，手续费${feeAmount}元，实际放款金额${actualAmount}元。请登录蘑菇伙伴APP查看详情。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(14, 3, '租金宝放款', '[租金宝放款]您的租金宝已经成功放款，对应房源${roomInfo}，租客${renterName}, 租金总额${loanAmount}元，保证金${depositAmount}元，手续费${feeAmount}元，实际放款金额${actualAmount}元。请登录蘑菇伙伴APP查看详情。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(15, 1, '租金宝审核通过', '[租金宝]您的租金宝申请已审核通过，可办理后续业务。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(15, 3, '租金宝审核通过', '[租金宝]您的租金宝申请已审核通过，可办理后续业务。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(16, 1, '预约带看申请', '${name}你好，${roomInfo}房源有新预约带看需求，带看时间：${lookTime}，租客姓名：${renterName},，手机号码：${renterPhoneNum}。请尽快与租客电话沟通联系', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(16, 3, '预约带看申请', '${name}你好，${roomInfo}房源有新预约带看需求，带看时间：${lookTime}，租客姓名：${renterName},，手机号码：${renterPhoneNum}。请尽快与租客电话沟通联系', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(17, 1, '账户充值', '[账户充值]您在“蘑菇伙伴”账户充值了${money}元。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(17, 3, '账户充值', '[账户充值]您在“蘑菇伙伴”账户充值了${money}元。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(18, 1, '豁免操作', '${communityName}小区${building}栋${flatRoomNum}号Room${roomName}租客${realName}通过转账或现金支付了账单，请及时确认。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(18, 3, '豁免操作', '${communityName}小区${building}栋${flatRoomNum}号Room${roomName}租客${realName}通过转账或现金支付了账单，请及时确认。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(19, 1, '豁免操作', '${communityName}${flatRoomNum}号租客${realName}通过转账或现金支付了账单，请及时确认。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(19, 3, '豁免操作', '${communityName}${flatRoomNum}号租客${realName}通过转账或现金支付了账单，请及时确认。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(20, 1, '蘑菇宝已通过', '[蘑菇宝已通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝申请已通过审批，等待放款中，请知悉。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(20, 3, '蘑菇宝已通过', '[蘑菇宝已通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝申请已通过审批，等待放款中，请知悉。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(21, 1, '补录租约确认', '租客${realName},同意了您${communityName}小区${building}栋${flatRoomNum}号Room${roomName}的补录租约。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(21, 3, '补录租约确认', '租客${realName},同意了您${communityName}小区${building}栋${flatRoomNum}号Room${roomName}的补录租约。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(22, 1, '补录租约确认', '租客${realName},同意了您${communityName}${flatRoomNum}号的补录租约。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(22, 3, '补录租约确认', '租客${realName},同意了您${communityName}${flatRoomNum}号的补录租约。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(23, 1, '补录租约意见', '租客${realName},不同意您${communityName}小区${building}栋${flatRoomNum}号Room${roomName}的补录租约，请及时联系与其沟通。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(23, 3, '补录租约意见', '租客${realName},不同意您${communityName}小区${building}栋${flatRoomNum}号Room${roomName}的补录租约，请及时联系与其沟通。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(24, 1, '补录租约意见', '租客${realName},不同意您${communityName}${flatRoomNum}号的补录租约，请及时联系与其沟通。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(24, 3, '补录租约意见', '租客${realName},不同意您${communityName}${flatRoomNum}号的补录租约，请及时联系与其沟通。', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(25, 1, '租金宝逾期，租客逾期', '[租金宝逾期]您的租金宝已经逾期${overDue}天，请通知租客${renterName}（${roomInfo}）及时支付本月房租，否则您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(25, 3, '租金宝逾期，租客逾期', '[租金宝逾期]您的租金宝已经逾期${overDue}天，请通知租客${renterName}（${roomInfo}）及时支付本月房租，否则您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(26, 1, '租金宝逾期，租客逾期', '[租金宝逾期]您的租金宝已经逾期${overDue}天，请通知租客${renterName}（${roomInfo}）及时支付本月房租，否则明天您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(26, 3, '租金宝逾期，租客逾期', '[租金宝逾期]您的租金宝已经逾期${overDue}天，请通知租客${renterName}（${roomInfo}）及时支付本月房租，否则明天您将需要买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(27, 1, '租金宝已终止，租客逾期', '[租金宝已终止]租客${renterName}（${roomInfo}）蘑菇宝逾期未支付租金，已经被强制退房，请及时处理。对应的租金宝已经中止，请确保个人帐户余额留有足够金额${countAmount}元，买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(27, 3, '租金宝已终止，租客逾期', '[租金宝已终止]租客${renterName}（${roomInfo}）蘑菇宝逾期未支付租金，已经被强制退房，请及时处理。对应的租金宝已经中止，请确保个人帐户余额留有足够金额${countAmount}元，买回租金宝并支付相应手续费和滞纳金。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(28, 1, '蘑菇宝终审不通过', '[蘑菇宝终审不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝终审不通过，此单不再提供租金宝，请您与租客协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(28, 3, '蘑菇宝终审不通过', '[蘑菇宝终审不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝终审不通过，此单不再提供租金宝，请您与租客协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(29, 1, '蘑菇宝终审不通过', '[蘑菇宝终审不通过]您的蘑菇宝付一押一终审不通过，请您与房东协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(29, 3, '蘑菇宝终审不通过', '[蘑菇宝终审不通过]您的蘑菇宝付一押一终审不通过，请您与房东协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(30, 1, '蘑菇宝首次申请不通过', '[蘑菇宝首次申请不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝首次申请审批失败，请协助通知租客及时提交修改资料。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(30, 3, '蘑菇宝首次申请不通过', '[蘑菇宝首次申请不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝首次申请审批失败，请协助通知租客及时提交修改资料。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(31, 1, '蘑菇宝审批不通过', '[蘑菇宝审批不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝申请失败，此单将无再提供租金宝，请您与租客协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(31, 3, '蘑菇宝审批不通过', '[蘑菇宝审批不通过]您的租客${renterName}，对应房源${roomInfo}，蘑菇宝申请失败，此单将无再提供租金宝，请您与租客协商变更付款方式重新签约。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(32, 1, '蘑菇宝租客成功支付租金', '[蘑菇宝租客成功支付租金]${address}租客${realName}已成功通过蘑菇宝付款方式支付了本期租金。', 1, 1, '', NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(32, 3, '蘑菇宝租客成功支付租金', '[蘑菇宝租客成功支付租金]${address}租客${realName}已成功通过蘑菇宝付款方式支付了本期租金。', 1, 1, '', NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(33, 3, '租金宝买回成功，租客逾期5天', '[租金宝买回成功]租客${renterName}对应的租金宝买回成功,买回总金额${countMoney}元。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(34, 3, '${roomInfo}投诉已解决', '${roomInfo}的投诉申请已解决，点击查看', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(35, 3, '${roomInfo}投诉已撤销', '${roomInfo}的投诉申请已撤销，点击查看', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(36, 3, '${roomInfo}已提交退房', '有一条退房消息', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(37, 3, '租金宝申请已提交', '[租金宝]您的租金宝申请已提交，请尽快向蘑菇租房提交相关资料进行审核。蘑菇租房400-800-4949', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(38, 3, '${roomInfo}的报修已解决', '${roomInfo}的报修已解决，点击查看', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(39, 3, '${roomInfo}的报修已撤销', '${roomInfo}的报修已撤销，点击查看', 1, 1, NULL, NULL);
INSERT INTO mesg_subtemplet (templetId, templetType, templetTitle, templetContent, status, valid, outTempletId, jumpCode) VALUES(40, 3, '你有一笔新的签约资料等待审核', '你有一笔新的签约资料等待审核！', 1, 1, NULL, NULL);






