-- MySQL Script generated by MySQL Workbench
-- 2015年12月31日 星期四 10时26分12秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema acct
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `acct` DEFAULT CHARACTER SET utf8 ;
USE `acct` ;

-- -----------------------------------------------------
-- Table `acct`.`acct_bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_bill` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_bill` (
  `billId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单编号',
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '账单总金额',
  `unpayAmount` DECIMAL(10,2) NOT NULL COMMENT '未结清费用',
  `acctId` INT(11) NOT NULL COMMENT '付款账号',
  `toAcctId` INT(11) NULL DEFAULT NULL COMMENT '收款账号',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(1024) NOT NULL COMMENT '备注',
  `origBillId` INT(32) NULL DEFAULT NULL COMMENT '关联账单编号',
  `deadline` DATE NULL DEFAULT NULL COMMENT '',
  `paidPenalty` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '已支付滞纳金额',
  PRIMARY KEY (`billId`)  COMMENT ''
  ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '账单表';
  
  -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账单表';


-- -----------------------------------------------------
-- Table `acct`.`acct_bill_chghistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_bill_chghistory` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_bill_chghistory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `billId` INT(11) NOT NULL COMMENT '账单id。参考账单表。',
  `busiType` INT(11) NOT NULL COMMENT '业务类型。参考comm_busitype表。',
  `oldAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单变更前金额',
  `oldUnpayAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '变更前的未付金额',
  `oldDeadline` DATE NULL DEFAULT NULL COMMENT '账单变更前截止日期',
  `newAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单变更后金额',
  `newUnpayAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '',
  `newDeadline` DATE NULL DEFAULT NULL COMMENT '账单变更后截止日期',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL DEFAULT NULL COMMENT '创建人id',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型。参考字段表useType。',
  `channel` TINYINT(4) NOT NULL COMMENT '操作渠道。参考字典表。',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)  COMMENT ''
 ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '账单变更履历表';

 -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账单变更履历表';
-- -----------------------------------------------------
-- Table `acct`.`acct_bill_tmp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_bill_tmp` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_bill_tmp` (
  `billId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单编号',
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '账单总金额',
  `unpayAmount` DECIMAL(10,2) NOT NULL COMMENT '未结清费用',
  `acctId` INT(11) NOT NULL COMMENT '付款账号',
  `toAcctId` INT(11) NULL DEFAULT NULL COMMENT '收款账号',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remark` VARCHAR(1024) NOT NULL COMMENT '备注',
  `origBillId` INT(32) NULL DEFAULT NULL COMMENT '关联账单编号',
  `deadline` DATE NULL DEFAULT NULL COMMENT '',
  `orderId` VARCHAR(32) NULL DEFAULT NULL COMMENT '订单号\n\n            ',
  `orderType` INT(6) NULL DEFAULT NULL COMMENT '订单类型\n\n            ',
  `fromTblName` VARCHAR(64) NULL DEFAULT NULL COMMENT '订单号从业务系统哪个表迁移过来的',
  `memo` VARCHAR(128) NULL DEFAULT NULL COMMENT '账单迁移备注',
  `paidPenalty` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '已支付滞纳金额',
  PRIMARY KEY (`billId`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '数据迁移用临时账单表';


-- -----------------------------------------------------
-- Table `acct`.`acct_billdtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_billdtl` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_billdtl` (
  `billDtlId` INT(32) NOT NULL AUTO_INCREMENT COMMENT '账单明细编号',
  `billId` INT(32) NOT NULL COMMENT '账单编号',
  `billDtlType` INT(11) NOT NULL COMMENT '账单明细类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额',
  PRIMARY KEY (`billDtlId`)  COMMENT ''
  ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '账单详情';
  -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账单详情';
-- -----------------------------------------------------
-- Table `acct`.`acct_billdtltype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_billdtltype` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_billdtltype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `billDtlType` INT(11) NOT NULL COMMENT '账单明细类型',
  `billDtlName` VARCHAR(64) NOT NULL COMMENT '账单明细名称',
  `status` TINYINT(4) NOT NULL COMMENT '0无效1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idx_billDtlType` (`billDtlType` ASC)  COMMENT '',
  UNIQUE INDEX `idx_billDtlName` (`billDtlName` ASC)  COMMENT ''
 ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '账单类型';
  -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账单类型';

-- -----------------------------------------------------
-- Table `acct`.`acct_billtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_billtype` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_billtype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `billName` VARCHAR(64) NOT NULL COMMENT '账单名称',
  `status` TINYINT(4) NOT NULL COMMENT '0无效1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  `penaltyRate` INT(4) NULL DEFAULT NULL COMMENT '滞纳金适用费率。单位：万分之一',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idx_billType` (`billType` ASC)  COMMENT '',
  UNIQUE INDEX `idx_billName` (`billName` ASC)  COMMENT ''
  ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '账单类型';
    -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账单类型';

-- -----------------------------------------------------
-- Table `acct`.`acct_billtypetofundtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_billtypetofundtype` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_billtypetofundtype` (
  `billType` INT(11) NOT NULL COMMENT '账单类型',
  `fromFundType` INT(32) NOT NULL COMMENT '扣款资金类型',
  `toFundType` INT(32) NOT NULL COMMENT '收款资金类型',
  PRIMARY KEY (`billType`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '账单类型与资金抵扣方式';


-- -----------------------------------------------------
-- Table `acct`.`acct_busibilldtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_busibilldtl` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_busibilldtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doneCode` INT(11) NOT NULL COMMENT '流水主表ID',
  `billId` INT(11) NOT NULL COMMENT '账单号',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额，账单费用增加为正',
  `beforeAmount` DECIMAL(10,2) NOT NULL COMMENT '支付前金额',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_doneCode` (`doneCode` ASC)  COMMENT '',
  INDEX `idx_billId` (`billId` ASC)  COMMENT ''
 ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '流水账单表';
  -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '流水账单表';

-- -----------------------------------------------------
-- Table `acct`.`acct_busifeedtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_busifeedtl` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_busifeedtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doneCode` INT(32) NOT NULL COMMENT '流水主表ID',
  `acctId` INT(11) NOT NULL COMMENT '账号id',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额，入款为正',
  `fundChannel` INT(2) NOT NULL COMMENT '渠道',
  `bankCode` VARCHAR(16) NOT NULL COMMENT '银行编号',
  `bankCard` VARCHAR(32) NOT NULL COMMENT '银行',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_doneCode` (`doneCode` ASC)  COMMENT '',
  INDEX `idx_acctId` (`acctId` ASC)  COMMENT ''
  ) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '资金来源';
   -- ) ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '资金来源';

-- -----------------------------------------------------
-- Table `acct`.`acct_busifunddtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_busifunddtl` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_busifunddtl` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doneCode` INT(32) NOT NULL COMMENT '业务流水id',
  `acctId` INT(32) NOT NULL COMMENT '账号id',
  `fundType` INT(11) NOT NULL COMMENT '资金类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '变化金额，余额增加为正',
  `beforeAmount` DECIMAL(10,2) NOT NULL COMMENT '变化前金额',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_doneCode` (`doneCode` ASC)  COMMENT '',
  INDEX `idx_acctId` (`acctId` ASC)  COMMENT ''
 )ENGINE = InnoDB  DEFAULT CHARSET = utf8 COMMENT = '资金';
  -- )ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '资金';

-- -----------------------------------------------------
-- Table `acct`.`acct_busirec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_busirec` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_busirec` (
  `doneCode` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `tradelogid` INT(11) NOT NULL COMMENT '支付行为外键',
  `busiType` INT(11) NOT NULL COMMENT '业务类型',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `reRecId` INT(11) NULL DEFAULT NULL COMMENT '退款关联ID',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `createBy` INT(11) NOT NULL COMMENT '操作人',
  `createByType` TINYINT(4) NOT NULL COMMENT '操作人类型',
  `channel` TINYINT(4) NOT NULL COMMENT '交易渠道',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`doneCode`)  COMMENT ''
  )ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '账务流水表';
   -- )ENGINE = InnoDB auto_increment=200000 DEFAULT CHARSET = utf8 COMMENT = '账务流水表';

-- -----------------------------------------------------
-- Table `acct`.`acct_check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_check` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_check` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '告警结果描述',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '修改之后是否已经审核',
  `checkResult` TINYINT(4) NULL DEFAULT NULL COMMENT '审核结果',
  `fundChannel` TINYINT(4) NULL DEFAULT NULL COMMENT '付款渠道',
  `checkDate` DATE NULL DEFAULT NULL COMMENT '对账日',
  `checkType` TINYINT(4) NULL DEFAULT NULL COMMENT '对账类型 余额 资金 业务',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '检查结果';


-- -----------------------------------------------------
-- Table `acct`.`acct_checkacctfunddetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checkacctfunddetail` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checkacctfunddetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `accountId` INT(11) NULL DEFAULT NULL COMMENT '个人帐户号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  `errorType` TINYINT(4) NULL DEFAULT NULL COMMENT '余额错误类型',
  PRIMARY KEY (`id`)  COMMENT ''
  )ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '个人帐户对账结果详情';


-- -----------------------------------------------------
-- Table `acct`.`acct_checkbillfunddetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checkbillfunddetail` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checkbillfunddetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `billId` INT(11) NULL DEFAULT NULL COMMENT '账单号',
  `waterBillId` INT(11) NULL DEFAULT NULL COMMENT '流水表中的billId',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(32) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '流水帐务，账单对账结果详情';


-- -----------------------------------------------------
-- Table `acct`.`acct_checkbilltradedetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checkbilltradedetail` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checkbilltradedetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '告警id',
  `tradeLogId` INT(11) NULL DEFAULT NULL COMMENT '支付行为id',
  `billTradeLogId` INT(11) NULL DEFAULT NULL COMMENT '帐务中的tradeLogId',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB  DEFAULT CHARACTER SET = utf8 COMMENT = '个人帐户对账结果详情';


-- -----------------------------------------------------
-- Table `acct`.`acct_checkbizdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checkbizdetail` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checkbizdetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '对账结果id  ,acct_check.id',
  `origBillNum` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务系统账单号',
  `billId` INT(11) NULL DEFAULT NULL COMMENT '账单号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '描述信息',
  PRIMARY KEY (`id`)  COMMENT ''
  )ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '业务系统与帐务系统对账结果详情';


-- -----------------------------------------------------
-- Table `acct`.`acct_checktradealipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checktradealipay` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checktradealipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务流水号',
  `fcDoneCode` VARCHAR(64) NOT NULL COMMENT '第三方流水号',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acct`.`acct_checktradedetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checktradedetail` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checktradedetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `checkId` INT(11) NULL DEFAULT NULL COMMENT '对账结果id  ,acct_check.id',
  `tradeNo` VARCHAR(32) NULL DEFAULT NULL COMMENT '交易编号',
  `oppoTradeNo` VARCHAR(32) NULL DEFAULT NULL COMMENT '支付商付款流水号',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `fixed` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经处理',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  `verified` TINYINT(4) NULL DEFAULT NULL COMMENT '是否已经审核',
  `fundChannel` INT(11) NULL DEFAULT NULL COMMENT '付款渠道',
  `content` VARCHAR(100) NULL DEFAULT NULL COMMENT '错误描述',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '检查交易结果详情';


-- -----------------------------------------------------
-- Table `acct`.`acct_checktradeweixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_checktradeweixin` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_checktradeweixin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务流水号',
  `fcDoneCode` VARCHAR(64) NOT NULL COMMENT '第三方流水号',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acct`.`acct_fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_fund` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_fund` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `acctId` INT(11) NOT NULL COMMENT '账号',
  `fundType` INT(11) NOT NULL COMMENT '资金类型',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '金额',
  `frozen` DECIMAL(10,2) NOT NULL COMMENT '冻结金额',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `accountId_fundType_unique` (`acctId` ASC, `fundType` ASC)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '账号余额表';


-- -----------------------------------------------------
-- Table `acct`.`acct_fundtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_fundtype` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_fundtype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `fundCode` INT NOT NULL COMMENT '唯一编码',
  `fundName` VARCHAR(20) NOT NULL COMMENT '名称',
  `status` TINYINT(4) NOT NULL COMMENT '状态，0无效，1有效',
  `sort` INT(11) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '资金类型';


-- -----------------------------------------------------
-- Table `acct`.`acct_passwordlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_passwordlog` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_passwordlog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '日志id',
  `acctId` INT(11) NOT NULL COMMENT '会员编号',
  `busiType` INT(11) NOT NULL COMMENT '访问类型',
  `accessResult` VARCHAR(32) NOT NULL COMMENT '访问结果',
  `accessTime` DATETIME NOT NULL COMMENT '访问时间',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '日志';


-- -----------------------------------------------------
-- Table `acct`.`acct_refund_alipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_refund_alipay` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_refund_alipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `biz_orderid` VARCHAR(30) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '业务类型',
  `notify_time` DATETIME NOT NULL COMMENT ' 格式为 yyyy-MM-dd HH:mm:ss ',
  `notify_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '通知的类型   业务类型',
  `notify_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '通知校验的ID ',
  `sign_type` VARCHAR(10) NULL DEFAULT NULL COMMENT '固定取值为 RSA   ',
  `sign` VARCHAR(1024) NULL DEFAULT NULL COMMENT '签名',
  `out_trade_no` VARCHAR(64) NOT NULL COMMENT '对应商户网站的订单系统中的 唯一订单号，非支付宝交易号。                                                                                                                           \n\n                                                                                                                                需保证在商户网站中的唯一性。 是请求时对应的参数，原样返 回',
  `subject` VARCHAR(128) NULL DEFAULT NULL COMMENT '商品的标题/交易标题/订单标题 /订单关键字等。 它在支付宝的交易明细中排在 第一列，对于财务对账尤为重 要。是请求时对应的参数，原样 通知回来。  ',
  `payment_type` VARCHAR(4) NULL DEFAULT NULL COMMENT '支付类型。默认值为：1（商品 购买                   ',
  `trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '该交易在支付宝系统中的交易 流水号。 最短 16 位，最长 64 位',
  `trade_status` VARCHAR(20) NULL DEFAULT NULL COMMENT '交易状态',
  `seller_id` VARCHAR(30) NULL DEFAULT NULL COMMENT '卖家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `seller_email` VARCHAR(100) NULL DEFAULT NULL COMMENT '卖家支付宝账号，可以是 email 和手机号码。',
  `buyer_id` VARCHAR(30) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号',
  `buyer_email` VARCHAR(100) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字。',
  `total_fee` DOUBLE NULL DEFAULT NULL COMMENT '该笔订单的总金额。 请求时对应的参数，原样通知回 来。 ',
  `quantity` DOUBLE NULL DEFAULT NULL COMMENT '购买数量，',
  `price` DOUBLE NULL DEFAULT NULL COMMENT 'price 等于 total_fee',
  `body` VARCHAR(512) NULL DEFAULT NULL COMMENT '该笔订单的备注',
  `gmt_create` DATETIME NULL DEFAULT NULL COMMENT '该笔交易创建的时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `gmt_payment` DATETIME NULL DEFAULT NULL COMMENT '该笔交易的买家付款时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `is_total_fee_adjust` VARCHAR(1) NULL DEFAULT NULL COMMENT '该交易是否调整过价格 ',
  `use_coupon` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在交易过程中使用了红包',
  `discount` VARCHAR(10) NULL DEFAULT NULL COMMENT ' 支付宝系统会把 discount 的值 加到交易金额上，如果有折扣， 本参数为负数，单位为元 ',
  `refund_status` VARCHAR(20) NULL DEFAULT NULL COMMENT '取值范围请参见“11.4  退款状 态”',
  `gmt_refund` DATETIME NULL DEFAULT NULL COMMENT '卖家退款的时间，退款通知时会 发送。 格式为 yyyy-MM-dd HH:mm:ss',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '支付宝退款记录';


-- -----------------------------------------------------
-- Table `acct`.`acct_speciallist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_speciallist` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_speciallist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `acctId` INT(11) NULL DEFAULT NULL COMMENT '账号id',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL DEFAULT NULL COMMENT '创建人',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型',
  `updateTime` DATE NULL DEFAULT NULL COMMENT '更新时间',
  `updateBy` INT(11) NULL DEFAULT NULL COMMENT '更新人',
  `udpateByType` TINYINT(4) NULL DEFAULT NULL COMMENT '更新人类型',
  `blackType` TINYINT(4) NULL DEFAULT NULL COMMENT '黑名单类型',
  `status` TINYINT(4) NULL DEFAULT NULL COMMENT '状态，0无效，1有效',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '账号黑白灰名单';


-- -----------------------------------------------------
-- Table `acct`.`acct_tradelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_tradelog` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_tradelog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `soDoneCode` VARCHAR(64) NOT NULL COMMENT '业务侧流水号',
  `busiType` INT(11) NOT NULL COMMENT '业务类型 详见业务类型表',
  `channel` TINYINT(4) NOT NULL COMMENT '操作渠道  租客APP：0 ， 房东APP：1，房东PC：2 ，bs系统：3',
  `fundChannel` INT(4) NULL DEFAULT NULL COMMENT '资金渠道 支付宝：1,，微信：2，维金：3，余额：4',
  `fcDoneCode` VARCHAR(64) NULL DEFAULT NULL COMMENT '第三方平台交易ID',
  `useFund` TINYINT(4) NOT NULL COMMENT '是否使用资金 1:是 0：不是',
  `billId` INT(32) NULL DEFAULT NULL COMMENT '账单ID  ',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `createByType` INT(11) NOT NULL COMMENT '创建人类型 租客：0 ，房东：1，MOGO员工：2',
  `createBy` INT(11) NOT NULL COMMENT '创建人',
  `updateTime` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `status` INT(2) NULL COMMENT '0原始状态，1支付完成，2支付撤销',
  `remark` VARCHAR(256) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '交易行为日志';


-- -----------------------------------------------------
-- Table `acct`.`acct_tradelog_alipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_tradelog_alipay` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_tradelog_alipay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `biz_orderid` INT(11) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务类型',
  `notify_time` DATETIME NULL DEFAULT NULL COMMENT '通知的发送时间。 格式为 yyyy-MM-dd HH:mm:ss',
  `notify_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '通知的类型',
  `notify_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '通知校验的ID',
  `sign_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '固定取值为 RSA',
  `sign` VARCHAR(1024) NULL DEFAULT NULL COMMENT '签名',
  `out_trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '对应商户网站的订单系统中的 唯一订单号，非支付宝交易号。 需保证在商户网站中的唯一性。 是请求时对应的参数，原样返 回。',
  `subject` VARCHAR(128) NULL DEFAULT NULL COMMENT '商品的标题/交易标题/订单标题 /订单关键字等。 它在支付宝的交易明细中排在 第一列，对于财务对账尤为重 要。是请求时对应的参数，原样 通知回来。',
  `payment_type` VARCHAR(4) NULL DEFAULT NULL COMMENT '支付类型。默认值为：1（商品 购买）',
  `trade_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '该交易在支付宝系统中的交易 流水号。 最短 16 位，最长 64 位。',
  `trade_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '交易状态，取值范围请参见 “11.3 交易状态”',
  `seller_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '卖家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `seller_email` VARCHAR(128) NULL DEFAULT NULL COMMENT '卖家支付宝账号，可以是 email 和手机号码。',
  `buyer_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '买家支付宝账号对应的支付宝 唯一用户号。 以 2088 开头的纯 16 位数字',
  `buyer_email` VARCHAR(128) NULL DEFAULT NULL COMMENT '买家支付宝账号，可以是 Email 或手机号码',
  `total_fee` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '该笔订单的总金额。 请求时对应的参数，原样通知回 来。',
  `quantity` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '购买数量，固定取值为 1（请求 时使用的是 total_fee）。',
  `price` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'price 等于 total_fee（请求时使 用的是 total_fee）',
  `body` VARCHAR(512) NULL DEFAULT NULL COMMENT '该笔订单的备注、描述、明细等。 对应请求时的 body 参数，原样 通知回来。',
  `gmt_create` DATETIME NULL DEFAULT NULL COMMENT '该笔交易创建的时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `gmt_payment` DATETIME NULL DEFAULT NULL COMMENT '该笔交易的买家付款时间。 格式为 yyyy-MM-dd HH:mm:ss。',
  `is_total_fee_adjust` VARCHAR(1) NULL DEFAULT NULL COMMENT '该交易是否调整过价格',
  `use_coupon` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否在交易过程中使用了红包',
  `discount` VARCHAR(16) NULL DEFAULT NULL COMMENT '支付宝系统会把 discount 的值 加到交易金额上，如果有折扣， 本参数为负数，单位为元',
  `refund_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '取值范围请参见“11.4 退款状 态”',
  `gmt_refund` DATETIME NULL DEFAULT NULL COMMENT '卖家退款的时间，退款通知时会 发送。 格式为 yyyy-MM-dd HH:mm:ss。',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '支付宝交易日志';


-- -----------------------------------------------------
-- Table `acct`.`acct_tradelog_weixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_tradelog_weixin` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_tradelog_weixin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `biz_orderid` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务订单ID',
  `biz_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '业务类型',
  `return_code` VARCHAR(16) NULL DEFAULT NULL COMMENT 'SUCCESS/FAIL 此字段是通信标识，非交易标识，交易是否成功需要查看result_code来判断',
  `return_msg` VARCHAR(128) NULL DEFAULT NULL COMMENT '返回信息，如非空，为错误原因 签名失败 参数格式校验错误',
  `appid` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信分配的公众账号ID（企业号corpid即为此appId）',
  `mch_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付分配的商户号',
  `device_info` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付分配的终端设备号，',
  `nonce_str` VARCHAR(32) NULL DEFAULT NULL COMMENT '随机字符串，不长于32位',
  `sign` VARCHAR(32) NULL DEFAULT NULL COMMENT '签名',
  `result_code` VARCHAR(16) NULL DEFAULT NULL COMMENT 'SUCCESS/FAIL',
  `err_code` VARCHAR(32) NULL DEFAULT NULL COMMENT '错误返回的信息描述',
  `err_code_des` VARCHAR(128) NULL DEFAULT NULL COMMENT '错误返回的信息描述',
  `openid` VARCHAR(128) NULL DEFAULT NULL COMMENT '用户在商户appid下的唯一标识',
  `is_subscribe` VARCHAR(1) NULL DEFAULT NULL COMMENT '用户是否关注公众账号，Y-关注，N-未关注，仅在公众账号类型支付有效',
  `trade_type` VARCHAR(16) NULL DEFAULT NULL COMMENT 'JSAPI、NATIVE、APP',
  `bank_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '银行类型',
  `total_fee` INT(11) NULL DEFAULT NULL COMMENT '订单总金额，单位为分',
  `fee_type` VARCHAR(8) NULL DEFAULT NULL COMMENT '货币类型，符合ISO4217标准的三位字母代码，默认人民币：CNY，',
  `cash_fee` INT(11) NULL DEFAULT NULL COMMENT '现金支付金额订单现金支付金额',
  `cash_fee_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '货币类型，符合ISO4217标准的三位字母代码，默认人民币：CNY',
  `coupon_fee` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠金额<=订单总金额，订单总金额-代金券或立减优惠金额=现金支付金额',
  `coupon_count` INT(11) NULL DEFAULT NULL COMMENT '代金券或立减优惠使用数量',
  `coupon_id_$n` VARCHAR(32) NULL DEFAULT NULL COMMENT '代金券或立减优惠ID,$n为下标，从0开始编号',
  `coupon_fee_$n` INT(11) NULL DEFAULT NULL COMMENT '单个代金券或立减优惠支付金额,$n为下标，从0开始编号',
  `transaction_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '微信支付订单号',
  `out_trade_no` VARCHAR(32) NULL DEFAULT NULL COMMENT '商户系统的订单号，与请求一致。',
  `attach` VARCHAR(128) NULL DEFAULT NULL COMMENT '商家数据包，原样返回',
  `time_end` VARCHAR(16) NULL DEFAULT NULL COMMENT '支付完成时间，格式为yyyyMMddHHmmss，如2009年12月25日9点10分10秒表示为20091225091010。',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '微信交易日志';


-- -----------------------------------------------------
-- Table `acct`.`acct_billdtl_chghistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_billdtl_chghistory` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_billdtl_chghistory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `billChgHistoryId` INT(11) NOT NULL COMMENT '账单变更履历表id',
  `billId` INT(11) NOT NULL COMMENT '账单id。参考账单表。',
  `billDtlId` INT(11) NOT NULL COMMENT '账单详细id。参考账单详细表。',
  `billDtlType` INT(11) NULL COMMENT '账单详细变更前类型',
  `oldAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单详细变更前金额',
  `newAmount` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '账单详细变更后金额',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createBy` INT(11) NULL COMMENT '创建人id',
  `createByType` TINYINT(4) NULL DEFAULT NULL COMMENT '创建人类型。参考字段表useType。',
  `remark` VARCHAR(256) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '账单变更履历表';


-- -----------------------------------------------------
-- Table `acct`.`acct_tradelog_unionpay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_tradelog_unionpay` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_tradelog_unionpay` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `billId` INT(11) NOT NULL COMMENT '账单ID',
  `merId` VARCHAR(15) NOT NULL COMMENT '商户代码.已被批准加入银联互联网系统的商户代码.',
  `orderId` VARCHAR(64) NOT NULL COMMENT '向银联发送的订单号',
  `orderRemark` VARCHAR(128) NULL COMMENT '订单描述',
  `payStatus` TINYINT NOT NULL COMMENT '支付状态。1:初始状态。2：支付成功。3:撤销支付成功。',
  `sendOrderRequest` TEXT(10240) NOT NULL COMMENT '订单推送请求参数。具体组成参考银联的订单推送接口API文档。json格式存储。',
  `sendOrderRequestTime` DATETIME NOT NULL COMMENT '订单推送请求时间',
  `tn` VARCHAR(21) NULL COMMENT '银联受理订单号.\n商户推送订单后银联系统返回该流水号，商户调用支付控件时使用',
  `payResultCallback` TEXT(10240) NULL COMMENT '支付结果回调参数。由银联系统回调、记录传入参数。json格式存储。',
  `payResultCallbackTime` DATETIME NULL COMMENT '支付结果回调时间',
  `queryId` VARCHAR(21) NULL COMMENT '查询流水号.\n由银联返回，用于在后续类交易中唯一标识一笔交易',
  `revokeRequest` TEXT(10240) NULL COMMENT '撤销支付请求参数。具体组成参考银联【撤销支付】接口API文档。json格式存储。',
  `revokeReuestTime` DATETIME NULL COMMENT '',
  `revokeRequestCallback` TEXT(10240) NULL COMMENT '支付撤销结果回调参数。由银联系统回调、传入参数。json格式存储。',
  `revokeRequestCallbackTime` DATETIME NULL COMMENT '',
  `revokeQueryId` VARCHAR(21) NULL COMMENT '消费撤销交易的交易流水号 供查询用',
  `revokeOrderId` VARCHAR(64) NULL COMMENT '发给银联的撤销支付订单id。该id与原支付订单id不同。',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_billId` (`billId` ASC)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '银联支付交易日志';


-- -----------------------------------------------------
-- Table `acct`.`acct_tradelog_unionpay_refund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acct`.`acct_tradelog_unionpay_refund` ;

CREATE TABLE IF NOT EXISTS `acct`.`acct_tradelog_unionpay_refund` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tradeLogUnionPayId` INT(11) NOT NULL COMMENT '银联交易logId',
  `refundRequest` TEXT(10240) NOT NULL COMMENT '退款请求参数。具体组成参考银联【退款】接口API文档。json格式存储。',
  `refundRequestTime` DATETIME NOT NULL COMMENT '退款请求时间',
  `refundRequestCallback` TEXT(10240) NULL COMMENT '支付退款结果回调参数。由银联系统回调、传入参数。json格式存储。',
  `refundRequestCallbackTime` DATETIME NULL COMMENT '退款回调时间',
  `refundQueryId` VARCHAR(21) NULL COMMENT '消费退款交易的交易流水号 供查询用',
  `refundAmount` DECIMAL(10,2) NOT NULL COMMENT '退款金额',
  `refundOrderId` VARCHAR(64) NOT NULL COMMENT '发给银联的退款订单id。该id与原支付订单id不同。',
  `refundStatus` TINYINT NOT NULL COMMENT '退款状态：0初始，1成功',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_tradeLogUnionPayId` (`tradeLogUnionPayId` ASC)  COMMENT ''
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COMMENT = '银联支付交易退款日志';


