-- 上海地铁1号线站点序号更新                            
UPDATE city_subway_station SET sort =1 WHERE id = 2177; 
UPDATE city_subway_station SET sort =2 WHERE id = 2178; 
UPDATE city_subway_station SET sort =3 WHERE id = 2179; 
UPDATE city_subway_station SET sort =4 WHERE id = 2180; 
UPDATE city_subway_station SET sort =5 WHERE id = 2181; 
UPDATE city_subway_station SET sort =6 WHERE id = 2182; 
UPDATE city_subway_station SET sort =7 WHERE id = 2183; 
UPDATE city_subway_station SET sort =8 WHERE id = 2184; 
UPDATE city_subway_station SET sort =9 WHERE id = 2185; 
UPDATE city_subway_station SET sort =10 WHERE id = 2186;
UPDATE city_subway_station SET sort =11 WHERE id = 2187;
UPDATE city_subway_station SET sort =12 WHERE id = 2188;
UPDATE city_subway_station SET sort =13 WHERE id = 2189;
UPDATE city_subway_station SET sort =14 WHERE id = 2190;
UPDATE city_subway_station SET sort =15 WHERE id = 2191;
UPDATE city_subway_station SET sort =16 WHERE id = 2192;
UPDATE city_subway_station SET sort =17 WHERE id = 2193;
UPDATE city_subway_station SET sort =18 WHERE id = 2194;
UPDATE city_subway_station SET sort =19 WHERE id = 2195;
UPDATE city_subway_station SET sort =20 WHERE id = 2196;
UPDATE city_subway_station SET sort =21 WHERE id = 2197;
UPDATE city_subway_station SET sort =22 WHERE id = 2198;
UPDATE city_subway_station SET sort =23 WHERE id = 2199;
UPDATE city_subway_station SET sort =24 WHERE id = 2200;
UPDATE city_subway_station SET sort =25 WHERE id = 2201;
UPDATE city_subway_station SET sort =26 WHERE id = 2202;
UPDATE city_subway_station SET sort =27 WHERE id = 2203;
UPDATE city_subway_station SET sort =28 WHERE id = 2204;

-- 上海地铁2号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2205; 
UPDATE city_subway_station SET sort = 2 WHERE id = 2206; 
UPDATE city_subway_station SET sort = 3 WHERE id = 2207; 
UPDATE city_subway_station SET sort = 4 WHERE id = 2208; 
UPDATE city_subway_station SET sort = 5 WHERE id = 2209; 
UPDATE city_subway_station SET sort = 6 WHERE id = 2210; 
UPDATE city_subway_station SET sort = 7 WHERE id = 2211; 
UPDATE city_subway_station SET sort = 8 WHERE id = 2212; 
UPDATE city_subway_station SET sort = 9 WHERE id = 2213; 
UPDATE city_subway_station SET sort = 10 WHERE id = 2214;
UPDATE city_subway_station SET sort = 11 WHERE id = 2215;
UPDATE city_subway_station SET sort = 12 WHERE id = 2216;
UPDATE city_subway_station SET sort = 13 WHERE id = 2217;
UPDATE city_subway_station SET sort = 14 WHERE id = 2218;
UPDATE city_subway_station SET sort = 15 WHERE id = 2219;
UPDATE city_subway_station SET sort = 16 WHERE id = 2220;
UPDATE city_subway_station SET sort = 17 WHERE id = 2221;
UPDATE city_subway_station SET sort = 18 WHERE id = 2222;
UPDATE city_subway_station SET sort = 19 WHERE id = 2223;
UPDATE city_subway_station SET sort = 20 WHERE id = 2224;
UPDATE city_subway_station SET sort = 21 WHERE id = 2225;
UPDATE city_subway_station SET sort = 22 WHERE id = 2226;
UPDATE city_subway_station SET sort = 23 WHERE id = 2227;
UPDATE city_subway_station SET sort = 24 WHERE id = 2228;
UPDATE city_subway_station SET sort = 25 WHERE id = 2229;
UPDATE city_subway_station SET sort = 26 WHERE id = 2230;
UPDATE city_subway_station SET sort = 27 WHERE id = 2231;
UPDATE city_subway_station SET sort = 28 WHERE id = 2232;
UPDATE city_subway_station SET sort = 29 WHERE id = 2233;
UPDATE city_subway_station SET sort = 30 WHERE id = 2234;

-- 上海地铁3号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2235;
UPDATE city_subway_station SET sort = 2 WHERE id = 2236;
UPDATE city_subway_station SET sort = 3 WHERE id = 2237;
UPDATE city_subway_station SET sort = 4 WHERE id = 2238;
UPDATE city_subway_station SET sort = 5 WHERE id = 2239;
UPDATE city_subway_station SET sort = 6 WHERE id = 2240;
UPDATE city_subway_station SET sort = 7 WHERE id = 2241;
UPDATE city_subway_station SET sort = 8 WHERE id = 2242;
UPDATE city_subway_station SET sort = 9 WHERE id = 2243;
UPDATE city_subway_station SET sort = 10 WHERE id = 2244;
UPDATE city_subway_station SET sort = 11 WHERE id = 2245;
UPDATE city_subway_station SET sort = 12 WHERE id = 2246;
UPDATE city_subway_station SET sort = 13 WHERE id = 2247;
UPDATE city_subway_station SET sort = 14 WHERE id = 2248;
UPDATE city_subway_station SET sort = 15 WHERE id = 2249;
UPDATE city_subway_station SET sort = 16 WHERE id = 2250;
UPDATE city_subway_station SET sort = 17 WHERE id = 2251;
UPDATE city_subway_station SET sort = 18 WHERE id = 2252;
UPDATE city_subway_station SET sort = 19 WHERE id = 2253;
UPDATE city_subway_station SET sort = 20 WHERE id = 2254;
UPDATE city_subway_station SET sort = 21 WHERE id = 2255;
UPDATE city_subway_station SET sort = 22 WHERE id = 2256;
UPDATE city_subway_station SET sort = 23 WHERE id = 2257;
UPDATE city_subway_station SET sort = 24 WHERE id = 2258;
UPDATE city_subway_station SET sort = 25 WHERE id = 2259;
UPDATE city_subway_station SET sort = 26 WHERE id = 2260;
UPDATE city_subway_station SET sort = 27 WHERE id = 2261;
UPDATE city_subway_station SET sort = 28 WHERE id = 2262;
UPDATE city_subway_station SET sort = 29 WHERE id = 2263;

-- 上海地铁4号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2264;
UPDATE city_subway_station SET sort = 2 WHERE id = 2265;
UPDATE city_subway_station SET sort = 3 WHERE id = 2266;
UPDATE city_subway_station SET sort = 4 WHERE id = 2267;
UPDATE city_subway_station SET sort = 5 WHERE id = 2268;
UPDATE city_subway_station SET sort = 6 WHERE id = 2269;
UPDATE city_subway_station SET sort = 7 WHERE id = 2270;
UPDATE city_subway_station SET sort = 8 WHERE id = 2271;
UPDATE city_subway_station SET sort = 9 WHERE id = 2272;
UPDATE city_subway_station SET sort = 10 WHERE id = 2273;
UPDATE city_subway_station SET sort = 11 WHERE id = 2274;
UPDATE city_subway_station SET sort = 12 WHERE id = 2275;
UPDATE city_subway_station SET sort = 13 WHERE id = 2276;
UPDATE city_subway_station SET sort = 14 WHERE id = 2277;
UPDATE city_subway_station SET sort = 15 WHERE id = 2278;
UPDATE city_subway_station SET sort = 16 WHERE id = 2279;
UPDATE city_subway_station SET sort = 17 WHERE id = 2280;
UPDATE city_subway_station SET sort = 18 WHERE id = 2281;
UPDATE city_subway_station SET sort = 19 WHERE id = 2282;
UPDATE city_subway_station SET sort = 20 WHERE id = 2283;
UPDATE city_subway_station SET sort = 21 WHERE id = 2284;
UPDATE city_subway_station SET sort = 22 WHERE id = 2285;
UPDATE city_subway_station SET sort = 23 WHERE id = 2286;
UPDATE city_subway_station SET sort = 24 WHERE id = 2287;
UPDATE city_subway_station SET sort = 25 WHERE id = 2288;
UPDATE city_subway_station SET sort = 26 WHERE id = 2289;

--  上海地铁5号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2290;
UPDATE city_subway_station SET sort = 2 WHERE id = 2291;
UPDATE city_subway_station SET sort = 3 WHERE id = 2292;
UPDATE city_subway_station SET sort = 4 WHERE id = 2293;
UPDATE city_subway_station SET sort = 5 WHERE id = 2294;
UPDATE city_subway_station SET sort = 6 WHERE id = 2295;
UPDATE city_subway_station SET sort = 7 WHERE id = 2296;
UPDATE city_subway_station SET sort = 8 WHERE id = 2297;
UPDATE city_subway_station SET sort = 9 WHERE id = 2298;
UPDATE city_subway_station SET sort = 10 WHERE id = 2299;
UPDATE city_subway_station SET sort = 11 WHERE id = 2300;

-- 上海地铁6号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2301;
UPDATE city_subway_station SET sort = 2 WHERE id = 2302;
UPDATE city_subway_station SET sort = 3 WHERE id = 2303;
UPDATE city_subway_station SET sort = 4 WHERE id = 2304;
UPDATE city_subway_station SET sort = 5 WHERE id = 2305;
UPDATE city_subway_station SET sort = 6 WHERE id = 2306;
UPDATE city_subway_station SET sort = 7 WHERE id = 2307;
UPDATE city_subway_station SET sort = 8 WHERE id = 2308;
UPDATE city_subway_station SET sort = 9 WHERE id = 2309;
UPDATE city_subway_station SET sort = 10 WHERE id = 2310;
UPDATE city_subway_station SET sort = 11 WHERE id = 2311;
UPDATE city_subway_station SET sort = 12 WHERE id = 2312;
UPDATE city_subway_station SET sort = 13 WHERE id = 2313;
UPDATE city_subway_station SET sort = 14 WHERE id = 2314;
UPDATE city_subway_station SET sort = 15 WHERE id = 2315;
UPDATE city_subway_station SET sort = 16 WHERE id = 2316;
UPDATE city_subway_station SET sort = 17 WHERE id = 2317;
UPDATE city_subway_station SET sort = 18 WHERE id = 2318;
UPDATE city_subway_station SET sort = 19 WHERE id = 2319;
UPDATE city_subway_station SET sort = 20 WHERE id = 2320;
UPDATE city_subway_station SET sort = 21 WHERE id = 2321;
UPDATE city_subway_station SET sort = 22 WHERE id = 2322;
UPDATE city_subway_station SET sort = 23 WHERE id = 2323;
UPDATE city_subway_station SET sort = 24 WHERE id = 2324;
UPDATE city_subway_station SET sort = 25 WHERE id = 2325;
UPDATE city_subway_station SET sort = 26 WHERE id = 2326;
UPDATE city_subway_station SET sort = 27 WHERE id = 2327;
UPDATE city_subway_station SET sort = 28 WHERE id = 2328;

-- 上海地铁7号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2329;
UPDATE city_subway_station SET sort = 2 WHERE id = 2330;
UPDATE city_subway_station SET sort = 3 WHERE id = 2331;
UPDATE city_subway_station SET sort = 4 WHERE id = 2332;
UPDATE city_subway_station SET sort = 5 WHERE id = 2333;
UPDATE city_subway_station SET sort = 6 WHERE id = 2334;
UPDATE city_subway_station SET sort = 7 WHERE id = 2335;
UPDATE city_subway_station SET sort = 8 WHERE id = 2336;
UPDATE city_subway_station SET sort = 9 WHERE id = 2337;
UPDATE city_subway_station SET sort = 10 WHERE id = 2338;
UPDATE city_subway_station SET sort = 11 WHERE id = 2339;
UPDATE city_subway_station SET sort = 12 WHERE id = 2340;
UPDATE city_subway_station SET sort = 13 WHERE id = 2341;
UPDATE city_subway_station SET sort = 14 WHERE id = 2342;
UPDATE city_subway_station SET sort = 15 WHERE id = 2343;
UPDATE city_subway_station SET sort = 16 WHERE id = 2344;
UPDATE city_subway_station SET sort = 17 WHERE id = 2345;
UPDATE city_subway_station SET sort = 18 WHERE id = 2346;
UPDATE city_subway_station SET sort = 19 WHERE id = 2347;
UPDATE city_subway_station SET sort = 20 WHERE id = 2348;
UPDATE city_subway_station SET sort = 21 WHERE id = 2349;
UPDATE city_subway_station SET sort = 22 WHERE id = 2350;
UPDATE city_subway_station SET sort = 23 WHERE id = 2351;
UPDATE city_subway_station SET sort = 24 WHERE id = 2352;
UPDATE city_subway_station SET sort = 25 WHERE id = 2353;
UPDATE city_subway_station SET sort = 26 WHERE id = 2354;
UPDATE city_subway_station SET sort = 27 WHERE id = 2355;
UPDATE city_subway_station SET sort = 28 WHERE id = 2540;
UPDATE city_subway_station SET sort = 29 WHERE id = 2356;
UPDATE city_subway_station SET sort = 30 WHERE id = 2357;
UPDATE city_subway_station SET sort = 31 WHERE id = 2358;
UPDATE city_subway_station SET sort = 32 WHERE id = 2359;
UPDATE city_subway_station SET sort = 33 WHERE id = 2360;

-- 上海地铁8号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2361;
UPDATE city_subway_station SET sort = 2 WHERE id = 2362;
UPDATE city_subway_station SET sort = 3 WHERE id = 2363;
UPDATE city_subway_station SET sort = 4 WHERE id = 2364;
UPDATE city_subway_station SET sort = 5 WHERE id = 2365;
UPDATE city_subway_station SET sort = 6 WHERE id = 2366;
UPDATE city_subway_station SET sort = 7 WHERE id = 2367;
UPDATE city_subway_station SET sort = 8 WHERE id = 2368;
UPDATE city_subway_station SET sort = 9 WHERE id = 2369;
UPDATE city_subway_station SET sort = 10 WHERE id = 2370;
UPDATE city_subway_station SET sort = 11 WHERE id = 2371;
UPDATE city_subway_station SET sort = 12 WHERE id = 2372;
UPDATE city_subway_station SET sort = 13 WHERE id = 2373;
UPDATE city_subway_station SET sort = 14 WHERE id = 2374;
UPDATE city_subway_station SET sort = 15 WHERE id = 2375;
UPDATE city_subway_station SET sort = 16 WHERE id = 2376;
UPDATE city_subway_station SET sort = 17 WHERE id = 2377;
UPDATE city_subway_station SET sort = 18 WHERE id = 2378;
UPDATE city_subway_station SET sort = 19 WHERE id = 2379;
UPDATE city_subway_station SET sort = 20 WHERE id = 2380;
UPDATE city_subway_station SET sort = 21 WHERE id = 2381;
UPDATE city_subway_station SET sort = 22 WHERE id = 2382;
UPDATE city_subway_station SET sort = 23 WHERE id = 2383;
UPDATE city_subway_station SET sort = 24 WHERE id = 2384;
UPDATE city_subway_station SET sort = 25 WHERE id = 2385;
UPDATE city_subway_station SET sort = 26 WHERE id = 2386;
UPDATE city_subway_station SET sort = 27 WHERE id = 2387;
UPDATE city_subway_station SET sort = 28 WHERE id = 2388;
UPDATE city_subway_station SET sort = 29 WHERE id = 2389;
UPDATE city_subway_station SET sort = 30 WHERE id = 2390;

-- 上海地铁9号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2391;
UPDATE city_subway_station SET sort = 2 WHERE id = 2392;
UPDATE city_subway_station SET sort = 3 WHERE id = 2393;
UPDATE city_subway_station SET sort = 4 WHERE id = 2394;
UPDATE city_subway_station SET sort = 5 WHERE id = 2395;
UPDATE city_subway_station SET sort = 6 WHERE id = 2396;
UPDATE city_subway_station SET sort = 7 WHERE id = 2397;
UPDATE city_subway_station SET sort = 8 WHERE id = 2398;
UPDATE city_subway_station SET sort = 9 WHERE id = 2399;
UPDATE city_subway_station SET sort = 10 WHERE id = 2400;
UPDATE city_subway_station SET sort = 11 WHERE id = 2401;
UPDATE city_subway_station SET sort = 12 WHERE id = 2402;
UPDATE city_subway_station SET sort = 13 WHERE id = 2403;
UPDATE city_subway_station SET sort = 14 WHERE id = 2404;
UPDATE city_subway_station SET sort = 15 WHERE id = 2405;
UPDATE city_subway_station SET sort = 16 WHERE id = 2406;
UPDATE city_subway_station SET sort = 17 WHERE id = 2407;
UPDATE city_subway_station SET sort = 18 WHERE id = 2408;
UPDATE city_subway_station SET sort = 19 WHERE id = 2409;
UPDATE city_subway_station SET sort = 20 WHERE id = 2410;
UPDATE city_subway_station SET sort = 21 WHERE id = 2411;
UPDATE city_subway_station SET sort = 22 WHERE id = 2412;
UPDATE city_subway_station SET sort = 23 WHERE id = 2413;
UPDATE city_subway_station SET sort = 24 WHERE id = 2541;
UPDATE city_subway_station SET sort = 25 WHERE id = 2542;
UPDATE city_subway_station SET sort = 26 WHERE id = 2543;


-- 上海地铁10号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2414;
UPDATE city_subway_station SET sort = 2 WHERE id = 2415;
UPDATE city_subway_station SET sort = 3 WHERE id = 2416;
UPDATE city_subway_station SET sort = 4 WHERE id = 2417;
UPDATE city_subway_station SET sort = 5 WHERE id = 2418;
UPDATE city_subway_station SET sort = 6 WHERE id = 2419;
UPDATE city_subway_station SET sort = 7 WHERE id = 2420;
UPDATE city_subway_station SET sort = 8 WHERE id = 2421;
UPDATE city_subway_station SET sort = 9 WHERE id = 2422;
UPDATE city_subway_station SET sort = 10 WHERE id = 2423;
UPDATE city_subway_station SET sort = 11 WHERE id = 2424;
UPDATE city_subway_station SET sort = 12 WHERE id = 2425;
UPDATE city_subway_station SET sort = 13 WHERE id = 2426;
UPDATE city_subway_station SET sort = 14 WHERE id = 2427;
UPDATE city_subway_station SET sort = 15 WHERE id = 2428;
UPDATE city_subway_station SET sort = 16 WHERE id = 2429;
UPDATE city_subway_station SET sort = 17 WHERE id = 2430;
UPDATE city_subway_station SET sort = 18 WHERE id = 2431;
UPDATE city_subway_station SET sort = 19 WHERE id = 2432;
UPDATE city_subway_station SET sort = 20 WHERE id = 2433;
UPDATE city_subway_station SET sort = 21 WHERE id = 2434;
UPDATE city_subway_station SET sort = 22 WHERE id = 2435;
UPDATE city_subway_station SET sort = 23 WHERE id = 2436;
UPDATE city_subway_station SET sort = 24 WHERE id = 2437;
UPDATE city_subway_station SET sort = 25 WHERE id = 2438;
UPDATE city_subway_station SET sort = 26 WHERE id = 2439;
UPDATE city_subway_station SET sort = 27 WHERE id = 2440;
UPDATE city_subway_station SET sort = 28 WHERE id = 2441;
UPDATE city_subway_station SET sort = 26 WHERE id = 2442;
UPDATE city_subway_station SET sort = 27 WHERE id = 2443;
UPDATE city_subway_station SET sort = 28 WHERE id = 2444;

-- 上海地铁11号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3267;
UPDATE city_subway_station SET sort = 2 WHERE id = 3266;
UPDATE city_subway_station SET sort = 3 WHERE id = 2539;
UPDATE city_subway_station SET sort = 4 WHERE id = 2538;
UPDATE city_subway_station SET sort = 5 WHERE id = 2536;
UPDATE city_subway_station SET sort = 6 WHERE id = 2535;
UPDATE city_subway_station SET sort = 7 WHERE id = 2534;
UPDATE city_subway_station SET sort = 8 WHERE id = 2533;
UPDATE city_subway_station SET sort = 9 WHERE id = 2532;
UPDATE city_subway_station SET sort = 10 WHERE id = 2531;
UPDATE city_subway_station SET sort = 11 WHERE id = 2530;
UPDATE city_subway_station SET sort = 12 WHERE id = 2529;
UPDATE city_subway_station SET sort = 13 WHERE id = 2528;
UPDATE city_subway_station SET sort = 14 WHERE id = 2527;
UPDATE city_subway_station SET sort = 15 WHERE id = 2445;
UPDATE city_subway_station SET sort = 16 WHERE id = 2446;
UPDATE city_subway_station SET sort = 17 WHERE id = 2447;
UPDATE city_subway_station SET sort = 18 WHERE id = 2448;
UPDATE city_subway_station SET sort = 19 WHERE id = 2449;
UPDATE city_subway_station SET sort = 20 WHERE id = 2450;
UPDATE city_subway_station SET sort = 21 WHERE id = 2451;
UPDATE city_subway_station SET sort = 22 WHERE id = 2452;
UPDATE city_subway_station SET sort = 23 WHERE id = 2453;
UPDATE city_subway_station SET sort = 24 WHERE id = 2454;
UPDATE city_subway_station SET sort = 25 WHERE id = 2455;
UPDATE city_subway_station SET sort = 26 WHERE id = 2456;
UPDATE city_subway_station SET sort = 27 WHERE id = 2457;
UPDATE city_subway_station SET sort = 28 WHERE id = 2458;
UPDATE city_subway_station SET sort = 29 WHERE id = 2459;
UPDATE city_subway_station SET sort = 30 WHERE id = 2460;
UPDATE city_subway_station SET sort = 27 WHERE id = 2461;
UPDATE city_subway_station SET sort = 28 WHERE id = 2462;
UPDATE city_subway_station SET sort = 29 WHERE id = 2463;
UPDATE city_subway_station SET sort = 30 WHERE id = 2464;
UPDATE city_subway_station SET sort = 31 WHERE id = 2526;
UPDATE city_subway_station SET sort = 32 WHERE id = 2525;
UPDATE city_subway_station SET sort = 33 WHERE id = 2524;

-- 上海地铁12号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2465;
UPDATE city_subway_station SET sort = 2 WHERE id = 2466;
UPDATE city_subway_station SET sort = 3 WHERE id = 2467;
UPDATE city_subway_station SET sort = 4 WHERE id = 2468;
UPDATE city_subway_station SET sort = 5 WHERE id = 2469;
UPDATE city_subway_station SET sort = 6 WHERE id = 2470;
UPDATE city_subway_station SET sort = 7 WHERE id = 2471;
UPDATE city_subway_station SET sort = 8 WHERE id = 2472;
UPDATE city_subway_station SET sort = 9 WHERE id = 2473;
UPDATE city_subway_station SET sort = 10 WHERE id = 2474;
UPDATE city_subway_station SET sort = 11 WHERE id = 2475;
UPDATE city_subway_station SET sort = 12 WHERE id = 2476;
UPDATE city_subway_station SET sort = 13 WHERE id = 2477;
UPDATE city_subway_station SET sort = 14 WHERE id = 2478;
UPDATE city_subway_station SET sort = 15 WHERE id = 2479;
UPDATE city_subway_station SET sort = 16 WHERE id = 2480;
UPDATE city_subway_station SET sort = 17 WHERE id = 2481;
UPDATE city_subway_station SET sort = 18 WHERE id = 2482;
UPDATE city_subway_station SET sort = 19 WHERE id = 2483;
UPDATE city_subway_station SET sort = 20 WHERE id = 2484;
UPDATE city_subway_station SET sort = 21 WHERE id = 2485;
UPDATE city_subway_station SET sort = 22 WHERE id = 2486;
UPDATE city_subway_station SET sort = 23 WHERE id = 2487;
UPDATE city_subway_station SET sort = 24 WHERE id = 2488;
UPDATE city_subway_station SET sort = 25 WHERE id = 2489;
UPDATE city_subway_station SET sort = 26 WHERE id = 2490;
UPDATE city_subway_station SET sort = 27 WHERE id = 2491;
UPDATE city_subway_station SET sort = 28 WHERE id = 2492;
UPDATE city_subway_station SET sort = 29 WHERE id = 2493;
UPDATE city_subway_station SET sort = 30 WHERE id = 2494;
UPDATE city_subway_station SET sort = 31 WHERE id = 2495;
UPDATE city_subway_station SET sort = 32 WHERE id = 2496;

-- 上海地铁13号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3268;
UPDATE city_subway_station SET sort = 2 WHERE id = 2498;
UPDATE city_subway_station SET sort = 3 WHERE id = 2499;
UPDATE city_subway_station SET sort = 4 WHERE id = 2500;
UPDATE city_subway_station SET sort = 5 WHERE id = 2501;
UPDATE city_subway_station SET sort = 6 WHERE id = 2502;
UPDATE city_subway_station SET sort = 7 WHERE id = 2503;
UPDATE city_subway_station SET sort = 8 WHERE id = 2504;
UPDATE city_subway_station SET sort = 9 WHERE id = 2505;
UPDATE city_subway_station SET sort = 10 WHERE id = 2506;
UPDATE city_subway_station SET sort = 11 WHERE id = 2507;
UPDATE city_subway_station SET sort = 12 WHERE id = 2508;
UPDATE city_subway_station SET sort = 13 WHERE id = 2509;
UPDATE city_subway_station SET sort = 14 WHERE id = 2510;
UPDATE city_subway_station SET sort = 15 WHERE id = 3269;
UPDATE city_subway_station SET sort = 16 WHERE id = 3270;
UPDATE city_subway_station SET sort = 17 WHERE id = 3271;
UPDATE city_subway_station SET sort = 18 WHERE id = 3272;
UPDATE city_subway_station SET sort = 19 WHERE id = 3273;

-- 上海地铁16号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2511;
UPDATE city_subway_station SET sort = 2 WHERE id = 2512;
UPDATE city_subway_station SET sort = 3 WHERE id = 2513;
UPDATE city_subway_station SET sort = 4 WHERE id = 2514;
UPDATE city_subway_station SET sort = 5 WHERE id = 2515;
UPDATE city_subway_station SET sort = 6 WHERE id = 2516;
UPDATE city_subway_station SET sort = 7 WHERE id = 2517;
UPDATE city_subway_station SET sort = 8 WHERE id = 2518;
UPDATE city_subway_station SET sort = 9 WHERE id = 2519;
UPDATE city_subway_station SET sort = 10 WHERE id = 3274;
UPDATE city_subway_station SET sort = 11 WHERE id = 3275;
UPDATE city_subway_station SET sort = 12 WHERE id = 3276;
UPDATE city_subway_station SET sort = 13 WHERE id = 3277;

-- 深圳地铁罗宝线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2747;
UPDATE city_subway_station SET sort = 2 WHERE id = 2748;
UPDATE city_subway_station SET sort = 3 WHERE id = 2749;
UPDATE city_subway_station SET sort = 4 WHERE id = 2750;
UPDATE city_subway_station SET sort = 5 WHERE id = 2751;
UPDATE city_subway_station SET sort = 6 WHERE id = 2752;
UPDATE city_subway_station SET sort = 7 WHERE id = 2753;
UPDATE city_subway_station SET sort = 8 WHERE id = 2754;
UPDATE city_subway_station SET sort = 9 WHERE id = 2755;
UPDATE city_subway_station SET sort = 10 WHERE id = 2756;
UPDATE city_subway_station SET sort = 11 WHERE id = 2757;
UPDATE city_subway_station SET sort = 12 WHERE id = 2758;
UPDATE city_subway_station SET sort = 13 WHERE id = 2759;
UPDATE city_subway_station SET sort = 14 WHERE id = 2760;
UPDATE city_subway_station SET sort = 15 WHERE id = 2761;
UPDATE city_subway_station SET sort = 16 WHERE id = 2762;
UPDATE city_subway_station SET sort = 17 WHERE id = 2763;
UPDATE city_subway_station SET sort = 18 WHERE id = 2764;
UPDATE city_subway_station SET sort = 19 WHERE id = 2765;
UPDATE city_subway_station SET sort = 20 WHERE id = 2766;
UPDATE city_subway_station SET sort = 21 WHERE id = 2767;
UPDATE city_subway_station SET sort = 22 WHERE id = 2768;
UPDATE city_subway_station SET sort = 23 WHERE id = 2769;
UPDATE city_subway_station SET sort = 24 WHERE id = 2770;
UPDATE city_subway_station SET sort = 25 WHERE id = 2771;
UPDATE city_subway_station SET sort = 26 WHERE id = 2772;
UPDATE city_subway_station SET sort = 27 WHERE id = 2773;
UPDATE city_subway_station SET sort = 28 WHERE id = 2774;
UPDATE city_subway_station SET sort = 29 WHERE id = 2775;
UPDATE city_subway_station SET sort = 30 WHERE id = 2776;

-- 深圳地铁蛇口线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2777;
UPDATE city_subway_station SET sort = 2 WHERE id = 2778;
UPDATE city_subway_station SET sort = 3 WHERE id = 2779;
UPDATE city_subway_station SET sort = 4 WHERE id = 2780;
UPDATE city_subway_station SET sort = 5 WHERE id = 2781;
UPDATE city_subway_station SET sort = 6 WHERE id = 2782;
UPDATE city_subway_station SET sort = 7 WHERE id = 2783;
UPDATE city_subway_station SET sort = 8 WHERE id = 2784;
UPDATE city_subway_station SET sort = 9 WHERE id = 2785;
UPDATE city_subway_station SET sort = 10 WHERE id = 2786;
UPDATE city_subway_station SET sort = 11 WHERE id = 2787;
UPDATE city_subway_station SET sort = 12 WHERE id = 2788;
UPDATE city_subway_station SET sort = 13 WHERE id = 2789;
UPDATE city_subway_station SET sort = 14 WHERE id = 2790;
UPDATE city_subway_station SET sort = 15 WHERE id = 2791;
UPDATE city_subway_station SET sort = 16 WHERE id = 2792;
UPDATE city_subway_station SET sort = 17 WHERE id = 2793;
UPDATE city_subway_station SET sort = 18 WHERE id = 2794;
UPDATE city_subway_station SET sort = 19 WHERE id = 2795;
UPDATE city_subway_station SET sort = 20 WHERE id = 2796;
UPDATE city_subway_station SET sort = 21 WHERE id = 2797;
UPDATE city_subway_station SET sort = 22 WHERE id = 2798;
UPDATE city_subway_station SET sort = 23 WHERE id = 2799;
UPDATE city_subway_station SET sort = 24 WHERE id = 2800;
UPDATE city_subway_station SET sort = 25 WHERE id = 2801;
UPDATE city_subway_station SET sort = 26 WHERE id = 2802;
UPDATE city_subway_station SET sort = 27 WHERE id = 2803;
UPDATE city_subway_station SET sort = 28 WHERE id = 2804;
UPDATE city_subway_station SET sort = 29 WHERE id = 2805;

-- 深圳地铁龙岗线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2806;
UPDATE city_subway_station SET sort = 2 WHERE id = 2807;
UPDATE city_subway_station SET sort = 3 WHERE id = 2808;
UPDATE city_subway_station SET sort = 4 WHERE id = 2809;
UPDATE city_subway_station SET sort = 5 WHERE id = 2810;
UPDATE city_subway_station SET sort = 6 WHERE id = 2811;
UPDATE city_subway_station SET sort = 7 WHERE id = 2812;
UPDATE city_subway_station SET sort = 8 WHERE id = 2813;
UPDATE city_subway_station SET sort = 9 WHERE id = 2814;
UPDATE city_subway_station SET sort = 10 WHERE id = 2815;
UPDATE city_subway_station SET sort = 11 WHERE id = 2816;
UPDATE city_subway_station SET sort = 12 WHERE id = 2817;
UPDATE city_subway_station SET sort = 13 WHERE id = 2818;
UPDATE city_subway_station SET sort = 14 WHERE id = 2819;
UPDATE city_subway_station SET sort = 15 WHERE id = 2820;
UPDATE city_subway_station SET sort = 16 WHERE id = 2821;
UPDATE city_subway_station SET sort = 17 WHERE id = 2822;
UPDATE city_subway_station SET sort = 18 WHERE id = 2823;
UPDATE city_subway_station SET sort = 19 WHERE id = 2824;
UPDATE city_subway_station SET sort = 20 WHERE id = 2825;
UPDATE city_subway_station SET sort = 21 WHERE id = 2826;
UPDATE city_subway_station SET sort = 22 WHERE id = 2827;
UPDATE city_subway_station SET sort = 23 WHERE id = 2828;
UPDATE city_subway_station SET sort = 24 WHERE id = 2829;
UPDATE city_subway_station SET sort = 25 WHERE id = 2830;
UPDATE city_subway_station SET sort = 26 WHERE id = 2831;
UPDATE city_subway_station SET sort = 27 WHERE id = 2832;
UPDATE city_subway_station SET sort = 28 WHERE id = 2833;
UPDATE city_subway_station SET sort = 29 WHERE id = 2834;
UPDATE city_subway_station SET sort = 30 WHERE id = 2835;

-- 深圳地铁龙华线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2836;
UPDATE city_subway_station SET sort = 2 WHERE id = 2837;
UPDATE city_subway_station SET sort = 3 WHERE id = 2838;
UPDATE city_subway_station SET sort = 4 WHERE id = 2839;
UPDATE city_subway_station SET sort = 5 WHERE id = 2840;
UPDATE city_subway_station SET sort = 6 WHERE id = 2841;
UPDATE city_subway_station SET sort = 7 WHERE id = 2842;
UPDATE city_subway_station SET sort = 8 WHERE id = 2843;
UPDATE city_subway_station SET sort = 9 WHERE id = 2844;
UPDATE city_subway_station SET sort = 10 WHERE id = 2845;
UPDATE city_subway_station SET sort = 11 WHERE id = 2846;
UPDATE city_subway_station SET sort = 12 WHERE id = 2847;
UPDATE city_subway_station SET sort = 13 WHERE id = 2848;
UPDATE city_subway_station SET sort = 14 WHERE id = 2849;
UPDATE city_subway_station SET sort = 15 WHERE id = 2850;

-- 深圳地铁环中线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2851;
UPDATE city_subway_station SET sort = 2 WHERE id = 2852;
UPDATE city_subway_station SET sort = 3 WHERE id = 2853;
UPDATE city_subway_station SET sort = 4 WHERE id = 2854;
UPDATE city_subway_station SET sort = 5 WHERE id = 2855;
UPDATE city_subway_station SET sort = 6 WHERE id = 2856;
UPDATE city_subway_station SET sort = 7 WHERE id = 2857;
UPDATE city_subway_station SET sort = 8 WHERE id = 2858;
UPDATE city_subway_station SET sort = 9 WHERE id = 2859;
UPDATE city_subway_station SET sort = 10 WHERE id = 2860;
UPDATE city_subway_station SET sort = 11 WHERE id = 2861;
UPDATE city_subway_station SET sort = 12 WHERE id = 2862;
UPDATE city_subway_station SET sort = 13 WHERE id = 2863;
UPDATE city_subway_station SET sort = 14 WHERE id = 2864;
UPDATE city_subway_station SET sort = 15 WHERE id = 2865;
UPDATE city_subway_station SET sort = 16 WHERE id = 2866;
UPDATE city_subway_station SET sort = 17 WHERE id = 2867;
UPDATE city_subway_station SET sort = 18 WHERE id = 2868;
UPDATE city_subway_station SET sort = 19 WHERE id = 2869;
UPDATE city_subway_station SET sort = 20 WHERE id = 2870;
UPDATE city_subway_station SET sort = 21 WHERE id = 2871;
UPDATE city_subway_station SET sort = 22 WHERE id = 2872;
UPDATE city_subway_station SET sort = 23 WHERE id = 2873;
UPDATE city_subway_station SET sort = 24 WHERE id = 2874;
UPDATE city_subway_station SET sort = 25 WHERE id = 2875;
UPDATE city_subway_station SET sort = 26 WHERE id = 2876;
UPDATE city_subway_station SET sort = 27 WHERE id = 2877;

-- 北京地铁2号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2878;
UPDATE city_subway_station SET sort = 2 WHERE id = 2879;
UPDATE city_subway_station SET sort = 3 WHERE id = 2880;
UPDATE city_subway_station SET sort = 4 WHERE id = 2881;
UPDATE city_subway_station SET sort = 5 WHERE id = 2882;
UPDATE city_subway_station SET sort = 6 WHERE id = 2883;
UPDATE city_subway_station SET sort = 7 WHERE id = 2884;
UPDATE city_subway_station SET sort = 8 WHERE id = 2885;
UPDATE city_subway_station SET sort = 9 WHERE id = 2886;
UPDATE city_subway_station SET sort = 10 WHERE id = 2887;
UPDATE city_subway_station SET sort = 11 WHERE id = 2888;
UPDATE city_subway_station SET sort = 12 WHERE id = 2889;
UPDATE city_subway_station SET sort = 13 WHERE id = 2890;
UPDATE city_subway_station SET sort = 14 WHERE id = 2891;
UPDATE city_subway_station SET sort = 15 WHERE id = 2892;
UPDATE city_subway_station SET sort = 16 WHERE id = 2893;
UPDATE city_subway_station SET sort = 17 WHERE id = 2894;
UPDATE city_subway_station SET sort = 18 WHERE id = 2895;

-- 北京地铁4号线大兴线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2896;
UPDATE city_subway_station SET sort = 2 WHERE id = 2897;
UPDATE city_subway_station SET sort = 3 WHERE id = 2898;
UPDATE city_subway_station SET sort = 4 WHERE id = 2899;
UPDATE city_subway_station SET sort = 5 WHERE id = 2900;
UPDATE city_subway_station SET sort = 6 WHERE id = 2901;
UPDATE city_subway_station SET sort = 7 WHERE id = 2902;
UPDATE city_subway_station SET sort = 8 WHERE id = 2903;
UPDATE city_subway_station SET sort = 9 WHERE id = 2904;
UPDATE city_subway_station SET sort = 10 WHERE id = 2905;
UPDATE city_subway_station SET sort = 11 WHERE id = 2906;
UPDATE city_subway_station SET sort = 12 WHERE id = 2907;
UPDATE city_subway_station SET sort = 13 WHERE id = 2908;
UPDATE city_subway_station SET sort = 14 WHERE id = 2909;
UPDATE city_subway_station SET sort = 15 WHERE id = 2910;
UPDATE city_subway_station SET sort = 16 WHERE id = 2911;
UPDATE city_subway_station SET sort = 17 WHERE id = 2912;
UPDATE city_subway_station SET sort = 18 WHERE id = 2913;
UPDATE city_subway_station SET sort = 19 WHERE id = 2914;
UPDATE city_subway_station SET sort = 20 WHERE id = 2915;
UPDATE city_subway_station SET sort = 21 WHERE id = 2916;
UPDATE city_subway_station SET sort = 22 WHERE id = 2917;
UPDATE city_subway_station SET sort = 23 WHERE id = 2918;
UPDATE city_subway_station SET sort = 24 WHERE id = 2919;
UPDATE city_subway_station SET sort = 25 WHERE id = 2920;
UPDATE city_subway_station SET sort = 26 WHERE id = 2921;
UPDATE city_subway_station SET sort = 27 WHERE id = 2922;
UPDATE city_subway_station SET sort = 28 WHERE id = 2923;
UPDATE city_subway_station SET sort = 29 WHERE id = 2924;
UPDATE city_subway_station SET sort = 30 WHERE id = 2925;
UPDATE city_subway_station SET sort = 31 WHERE id = 2926;
UPDATE city_subway_station SET sort = 32 WHERE id = 2927;
UPDATE city_subway_station SET sort = 33 WHERE id = 2928;
UPDATE city_subway_station SET sort = 34 WHERE id = 2929;
UPDATE city_subway_station SET sort = 35 WHERE id = 2930;

-- 北京地铁5号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2931;
UPDATE city_subway_station SET sort = 2 WHERE id = 2932;
UPDATE city_subway_station SET sort = 3 WHERE id = 2933;
UPDATE city_subway_station SET sort = 4 WHERE id = 2934;
UPDATE city_subway_station SET sort = 5 WHERE id = 2935;
UPDATE city_subway_station SET sort = 6 WHERE id = 2936;
UPDATE city_subway_station SET sort = 7 WHERE id = 2937;
UPDATE city_subway_station SET sort = 8 WHERE id = 2938;
UPDATE city_subway_station SET sort = 9 WHERE id = 2939;
UPDATE city_subway_station SET sort = 10 WHERE id = 2940;
UPDATE city_subway_station SET sort = 11 WHERE id = 2941;
UPDATE city_subway_station SET sort = 12 WHERE id = 2942;
UPDATE city_subway_station SET sort = 13 WHERE id = 2943;
UPDATE city_subway_station SET sort = 14 WHERE id = 2944;
UPDATE city_subway_station SET sort = 15 WHERE id = 2945;
UPDATE city_subway_station SET sort = 16 WHERE id = 2946;
UPDATE city_subway_station SET sort = 17 WHERE id = 2947;
UPDATE city_subway_station SET sort = 18 WHERE id = 2948;
UPDATE city_subway_station SET sort = 19 WHERE id = 2949;
UPDATE city_subway_station SET sort = 20 WHERE id = 2950;
UPDATE city_subway_station SET sort = 21 WHERE id = 2951;
UPDATE city_subway_station SET sort = 22 WHERE id = 2952;
UPDATE city_subway_station SET sort = 23 WHERE id = 2953;

-- 北京地铁6号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2954;
UPDATE city_subway_station SET sort = 2 WHERE id = 2955;
UPDATE city_subway_station SET sort = 3 WHERE id = 2956;
UPDATE city_subway_station SET sort = 4 WHERE id = 2957;
UPDATE city_subway_station SET sort = 5 WHERE id = 2958;
UPDATE city_subway_station SET sort = 6 WHERE id = 2959;
UPDATE city_subway_station SET sort = 7 WHERE id = 2960;
UPDATE city_subway_station SET sort = 8 WHERE id = 2961;
UPDATE city_subway_station SET sort = 9 WHERE id = 2962;
UPDATE city_subway_station SET sort = 10 WHERE id = 2963;
UPDATE city_subway_station SET sort = 11 WHERE id = 2964;
UPDATE city_subway_station SET sort = 12 WHERE id = 2965;
UPDATE city_subway_station SET sort = 13 WHERE id = 2966;
UPDATE city_subway_station SET sort = 14 WHERE id = 2967;
UPDATE city_subway_station SET sort = 15 WHERE id = 2968;
UPDATE city_subway_station SET sort = 16 WHERE id = 2969;
UPDATE city_subway_station SET sort = 17 WHERE id = 2970;
UPDATE city_subway_station SET sort = 18 WHERE id = 2971;
UPDATE city_subway_station SET sort = 19 WHERE id = 2972;
UPDATE city_subway_station SET sort = 20 WHERE id = 2973;
UPDATE city_subway_station SET sort = 21 WHERE id = 2974;
UPDATE city_subway_station SET sort = 22 WHERE id = 2975;
UPDATE city_subway_station SET sort = 23 WHERE id = 2976;
UPDATE city_subway_station SET sort = 24 WHERE id = 2977;
UPDATE city_subway_station SET sort = 25 WHERE id = 2978;
UPDATE city_subway_station SET sort = 26 WHERE id = 2979;

-- 北京地铁7号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 2980;
UPDATE city_subway_station SET sort = 2 WHERE id = 2981;
UPDATE city_subway_station SET sort = 3 WHERE id = 2982;
UPDATE city_subway_station SET sort = 4 WHERE id = 2983;
UPDATE city_subway_station SET sort = 5 WHERE id = 2984;
UPDATE city_subway_station SET sort = 6 WHERE id = 2985;
UPDATE city_subway_station SET sort = 7 WHERE id = 2986;
UPDATE city_subway_station SET sort = 8 WHERE id = 2987;
UPDATE city_subway_station SET sort = 9 WHERE id = 2988;
UPDATE city_subway_station SET sort = 10 WHERE id = 2989;
UPDATE city_subway_station SET sort = 11 WHERE id = 2990;
UPDATE city_subway_station SET sort = 12 WHERE id = 2991;
UPDATE city_subway_station SET sort = 13 WHERE id = 2992;
UPDATE city_subway_station SET sort = 14 WHERE id = 2993;
UPDATE city_subway_station SET sort = 15 WHERE id = 2994;
UPDATE city_subway_station SET sort = 16 WHERE id = 2995;
UPDATE city_subway_station SET sort = 17 WHERE id = 2996;
UPDATE city_subway_station SET sort = 18 WHERE id = 2997;
UPDATE city_subway_station SET sort = 19 WHERE id = 2998;
UPDATE city_subway_station SET sort = 20 WHERE id = 2999;
UPDATE city_subway_station SET sort = 21 WHERE id = 3000;

-- 北京地铁8号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3001;
UPDATE city_subway_station SET sort = 2 WHERE id = 3002;
UPDATE city_subway_station SET sort = 3 WHERE id = 3003;
UPDATE city_subway_station SET sort = 4 WHERE id = 3004;
UPDATE city_subway_station SET sort = 5 WHERE id = 3005;
UPDATE city_subway_station SET sort = 6 WHERE id = 3006;
UPDATE city_subway_station SET sort = 7 WHERE id = 3007;
UPDATE city_subway_station SET sort = 8 WHERE id = 3008;
UPDATE city_subway_station SET sort = 9 WHERE id = 3009;
UPDATE city_subway_station SET sort = 10 WHERE id = 3010;
UPDATE city_subway_station SET sort = 11 WHERE id = 3011;
UPDATE city_subway_station SET sort = 12 WHERE id = 3012;
UPDATE city_subway_station SET sort = 13 WHERE id = 3013;
UPDATE city_subway_station SET sort = 14 WHERE id = 3014;
UPDATE city_subway_station SET sort = 15 WHERE id = 3015;
UPDATE city_subway_station SET sort = 16 WHERE id = 3016;
UPDATE city_subway_station SET sort = 17 WHERE id = 3017;

-- 北京地铁9号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3018;
UPDATE city_subway_station SET sort = 2 WHERE id = 3019;
UPDATE city_subway_station SET sort = 3 WHERE id = 3020;
UPDATE city_subway_station SET sort = 4 WHERE id = 3021;
UPDATE city_subway_station SET sort = 5 WHERE id = 3022;
UPDATE city_subway_station SET sort = 6 WHERE id = 3023;
UPDATE city_subway_station SET sort = 7 WHERE id = 3024;
UPDATE city_subway_station SET sort = 8 WHERE id = 3025;
UPDATE city_subway_station SET sort = 9 WHERE id = 3026;
UPDATE city_subway_station SET sort = 10 WHERE id = 3027;
UPDATE city_subway_station SET sort = 11 WHERE id = 3028;
UPDATE city_subway_station SET sort = 12 WHERE id = 3029;
UPDATE city_subway_station SET sort = 13 WHERE id = 3030;

-- 北京地铁10号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3073;
UPDATE city_subway_station SET sort = 2 WHERE id = 3074;
UPDATE city_subway_station SET sort = 3 WHERE id = 3075;
UPDATE city_subway_station SET sort = 4 WHERE id = 3031;
UPDATE city_subway_station SET sort = 5 WHERE id = 3032;
UPDATE city_subway_station SET sort = 6 WHERE id = 3033;
UPDATE city_subway_station SET sort = 7 WHERE id = 3034;
UPDATE city_subway_station SET sort = 8 WHERE id = 3035;
UPDATE city_subway_station SET sort = 9 WHERE id = 3036;
UPDATE city_subway_station SET sort = 10 WHERE id = 3037;
UPDATE city_subway_station SET sort = 11 WHERE id = 3038;
UPDATE city_subway_station SET sort = 12 WHERE id = 3039;
UPDATE city_subway_station SET sort = 13 WHERE id = 3040;
UPDATE city_subway_station SET sort = 14 WHERE id = 3041;
UPDATE city_subway_station SET sort = 15 WHERE id = 3042;
UPDATE city_subway_station SET sort = 16 WHERE id = 3043;
UPDATE city_subway_station SET sort = 17 WHERE id = 3044;
UPDATE city_subway_station SET sort = 18 WHERE id = 3045;
UPDATE city_subway_station SET sort = 19 WHERE id = 3046;
UPDATE city_subway_station SET sort = 20 WHERE id = 3047;
UPDATE city_subway_station SET sort = 21 WHERE id = 3048;
UPDATE city_subway_station SET sort = 22 WHERE id = 3049;
UPDATE city_subway_station SET sort = 23 WHERE id = 3050;
UPDATE city_subway_station SET sort = 24 WHERE id = 3051;
UPDATE city_subway_station SET sort = 25 WHERE id = 3052;
UPDATE city_subway_station SET sort = 26 WHERE id = 3053;
UPDATE city_subway_station SET sort = 27 WHERE id = 3054;
UPDATE city_subway_station SET sort = 28 WHERE id = 3055;
UPDATE city_subway_station SET sort = 29 WHERE id = 3056;
UPDATE city_subway_station SET sort = 30 WHERE id = 3057;
UPDATE city_subway_station SET sort = 31 WHERE id = 3058;
UPDATE city_subway_station SET sort = 32 WHERE id = 3059;
UPDATE city_subway_station SET sort = 33 WHERE id = 3060;
UPDATE city_subway_station SET sort = 34 WHERE id = 3061;
UPDATE city_subway_station SET sort = 35 WHERE id = 3062;
UPDATE city_subway_station SET sort = 36 WHERE id = 3063;
UPDATE city_subway_station SET sort = 37 WHERE id = 3064;
UPDATE city_subway_station SET sort = 38 WHERE id = 3065;
UPDATE city_subway_station SET sort = 39 WHERE id = 3066;
UPDATE city_subway_station SET sort = 40 WHERE id = 3067;
UPDATE city_subway_station SET sort = 41 WHERE id = 3068;
UPDATE city_subway_station SET sort = 42 WHERE id = 3069;
UPDATE city_subway_station SET sort = 43 WHERE id = 3070;
UPDATE city_subway_station SET sort = 44 WHERE id = 3071;
UPDATE city_subway_station SET sort = 45 WHERE id = 3072;

-- 北京地铁13号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3076;
UPDATE city_subway_station SET sort = 2 WHERE id = 3077;
UPDATE city_subway_station SET sort = 3 WHERE id = 3078;
UPDATE city_subway_station SET sort = 4 WHERE id = 3079;
UPDATE city_subway_station SET sort = 5 WHERE id = 3080;
UPDATE city_subway_station SET sort = 6 WHERE id = 3081;
UPDATE city_subway_station SET sort = 7 WHERE id = 3082;
UPDATE city_subway_station SET sort = 8 WHERE id = 3083;
UPDATE city_subway_station SET sort = 9 WHERE id = 3084;
UPDATE city_subway_station SET sort = 10 WHERE id = 3085;
UPDATE city_subway_station SET sort = 11 WHERE id = 3086;
UPDATE city_subway_station SET sort = 12 WHERE id = 3087;
UPDATE city_subway_station SET sort = 13 WHERE id = 3088;
UPDATE city_subway_station SET sort = 14 WHERE id = 3089;
UPDATE city_subway_station SET sort = 15 WHERE id = 3090;
UPDATE city_subway_station SET sort = 16 WHERE id = 3091;

-- 北京地铁14号线西段站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3092;
UPDATE city_subway_station SET sort = 2 WHERE id = 3093;
UPDATE city_subway_station SET sort = 3 WHERE id = 3094;
UPDATE city_subway_station SET sort = 4 WHERE id = 3095;
UPDATE city_subway_station SET sort = 5 WHERE id = 3096;
UPDATE city_subway_station SET sort = 6 WHERE id = 3097;
UPDATE city_subway_station SET sort = 7 WHERE id = 3098;

-- 北京地铁14号线东段站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3099;
UPDATE city_subway_station SET sort = 2 WHERE id = 3100;
UPDATE city_subway_station SET sort = 3 WHERE id = 3101;
UPDATE city_subway_station SET sort = 4 WHERE id = 3102;
UPDATE city_subway_station SET sort = 5 WHERE id = 3103;
UPDATE city_subway_station SET sort = 6 WHERE id = 3104;
UPDATE city_subway_station SET sort = 7 WHERE id = 3105;
UPDATE city_subway_station SET sort = 8 WHERE id = 3106;
UPDATE city_subway_station SET sort = 9 WHERE id = 3107;
UPDATE city_subway_station SET sort = 10 WHERE id = 3108;

-- 北京地铁15号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3109;
UPDATE city_subway_station SET sort = 2 WHERE id = 3110;
UPDATE city_subway_station SET sort = 3 WHERE id = 3111;
UPDATE city_subway_station SET sort = 4 WHERE id = 3112;
UPDATE city_subway_station SET sort = 5 WHERE id = 3113;
UPDATE city_subway_station SET sort = 6 WHERE id = 3114;
UPDATE city_subway_station SET sort = 7 WHERE id = 3115;
UPDATE city_subway_station SET sort = 8 WHERE id = 3116;
UPDATE city_subway_station SET sort = 9 WHERE id = 3117;
UPDATE city_subway_station SET sort = 10 WHERE id = 3118;
UPDATE city_subway_station SET sort = 11 WHERE id = 3119;
UPDATE city_subway_station SET sort = 12 WHERE id = 3120;
UPDATE city_subway_station SET sort = 13 WHERE id = 3121;
UPDATE city_subway_station SET sort = 14 WHERE id = 3122;
UPDATE city_subway_station SET sort = 15 WHERE id = 3123;
UPDATE city_subway_station SET sort = 16 WHERE id = 3124;
UPDATE city_subway_station SET sort = 17 WHERE id = 3125;
UPDATE city_subway_station SET sort = 18 WHERE id = 3126;

-- 北京地铁八通线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3127;
UPDATE city_subway_station SET sort = 2 WHERE id = 3128;
UPDATE city_subway_station SET sort = 3 WHERE id = 3129;
UPDATE city_subway_station SET sort = 4 WHERE id = 3130;
UPDATE city_subway_station SET sort = 5 WHERE id = 3131;
UPDATE city_subway_station SET sort = 6 WHERE id = 3132;
UPDATE city_subway_station SET sort = 7 WHERE id = 3133;
UPDATE city_subway_station SET sort = 8 WHERE id = 3134;
UPDATE city_subway_station SET sort = 9 WHERE id = 3135;
UPDATE city_subway_station SET sort = 10 WHERE id = 3136;
UPDATE city_subway_station SET sort = 11 WHERE id = 3137;
UPDATE city_subway_station SET sort = 12 WHERE id = 3138;
UPDATE city_subway_station SET sort = 13 WHERE id = 3139;

-- 北京地铁昌平线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3140;
UPDATE city_subway_station SET sort = 2 WHERE id = 3141;
UPDATE city_subway_station SET sort = 3 WHERE id = 3142;
UPDATE city_subway_station SET sort = 4 WHERE id = 3143;
UPDATE city_subway_station SET sort = 5 WHERE id = 3144;
UPDATE city_subway_station SET sort = 6 WHERE id = 3145;
UPDATE city_subway_station SET sort = 7 WHERE id = 3146;

-- 北京地铁亦庄线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3147;
UPDATE city_subway_station SET sort = 2 WHERE id = 3148;
UPDATE city_subway_station SET sort = 3 WHERE id = 3149;
UPDATE city_subway_station SET sort = 4 WHERE id = 3150;
UPDATE city_subway_station SET sort = 5 WHERE id = 3151;
UPDATE city_subway_station SET sort = 6 WHERE id = 3152;
UPDATE city_subway_station SET sort = 7 WHERE id = 3153;
UPDATE city_subway_station SET sort = 8 WHERE id = 3154;
UPDATE city_subway_station SET sort = 9 WHERE id = 3155;
UPDATE city_subway_station SET sort = 10 WHERE id = 3156;
UPDATE city_subway_station SET sort = 11 WHERE id = 3157;
UPDATE city_subway_station SET sort = 12 WHERE id = 3158;
UPDATE city_subway_station SET sort = 13 WHERE id = 3159;

-- 北京地铁房山线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3160;
UPDATE city_subway_station SET sort = 2 WHERE id = 3161;
UPDATE city_subway_station SET sort = 3 WHERE id = 3162;
UPDATE city_subway_station SET sort = 4 WHERE id = 3163;
UPDATE city_subway_station SET sort = 5 WHERE id = 3164;
UPDATE city_subway_station SET sort = 6 WHERE id = 3165;
UPDATE city_subway_station SET sort = 7 WHERE id = 3166;
UPDATE city_subway_station SET sort = 8 WHERE id = 3167;
UPDATE city_subway_station SET sort = 9 WHERE id = 3168;
UPDATE city_subway_station SET sort = 10 WHERE id = 3169;
UPDATE city_subway_station SET sort = 11 WHERE id = 3170;

-- 北京地铁机场线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3171;
UPDATE city_subway_station SET sort = 2 WHERE id = 3172;
UPDATE city_subway_station SET sort = 3 WHERE id = 3173;
UPDATE city_subway_station SET sort = 3 WHERE id = 3174;

-- 北京地铁1号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3175;
UPDATE city_subway_station SET sort = 2 WHERE id = 3176;
UPDATE city_subway_station SET sort = 3 WHERE id = 3177;
UPDATE city_subway_station SET sort = 4 WHERE id = 3178;
UPDATE city_subway_station SET sort = 5 WHERE id = 3179;
UPDATE city_subway_station SET sort = 6 WHERE id = 3180;
UPDATE city_subway_station SET sort = 7 WHERE id = 3181;
UPDATE city_subway_station SET sort = 8 WHERE id = 3182;
UPDATE city_subway_station SET sort = 9 WHERE id = 3183;
UPDATE city_subway_station SET sort = 10 WHERE id = 3184;
UPDATE city_subway_station SET sort = 11 WHERE id = 3185;
UPDATE city_subway_station SET sort = 12 WHERE id = 3186;
UPDATE city_subway_station SET sort = 13 WHERE id = 3187;
UPDATE city_subway_station SET sort = 14 WHERE id = 3188;
UPDATE city_subway_station SET sort = 15 WHERE id = 3189;
UPDATE city_subway_station SET sort = 16 WHERE id = 3190;
UPDATE city_subway_station SET sort = 17 WHERE id = 3191;
UPDATE city_subway_station SET sort = 18 WHERE id = 3192;
UPDATE city_subway_station SET sort = 19 WHERE id = 3193;
UPDATE city_subway_station SET sort = 20 WHERE id = 3194;
UPDATE city_subway_station SET sort = 21 WHERE id = 3195;
UPDATE city_subway_station SET sort = 22 WHERE id = 3196;
UPDATE city_subway_station SET sort = 23 WHERE id = 3197;

-- 杭州地铁1号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3208;
UPDATE city_subway_station SET sort = 2 WHERE id = 3227;
UPDATE city_subway_station SET sort = 3 WHERE id = 3207;
UPDATE city_subway_station SET sort = 4 WHERE id = 3226;
UPDATE city_subway_station SET sort = 5 WHERE id = 3205;
UPDATE city_subway_station SET sort = 6 WHERE id = 3220;
UPDATE city_subway_station SET sort = 7 WHERE id = 3231;
UPDATE city_subway_station SET sort = 8 WHERE id = 3201;
UPDATE city_subway_station SET sort = 9 WHERE id = 3210;
UPDATE city_subway_station SET sort = 10 WHERE id = 3204;
UPDATE city_subway_station SET sort = 11 WHERE id = 3209;
UPDATE city_subway_station SET sort = 12 WHERE id = 3200;
UPDATE city_subway_station SET sort = 13 WHERE id = 3202;
UPDATE city_subway_station SET sort = 14 WHERE id = 3203;
UPDATE city_subway_station SET sort = 15 WHERE id = 3240;
UPDATE city_subway_station SET sort = 16 WHERE id = 3198;
UPDATE city_subway_station SET sort = 17 WHERE id = 3214;
UPDATE city_subway_station SET sort = 18 WHERE id = 3232;
UPDATE city_subway_station SET sort = 19 WHERE id = 3241;
UPDATE city_subway_station SET sort = 20 WHERE id = 3218;
UPDATE city_subway_station SET sort = 21 WHERE id = 3230;
UPDATE city_subway_station SET sort = 22 WHERE id = 3229;
UPDATE city_subway_station SET sort = 23 WHERE id = 3234;
UPDATE city_subway_station SET sort = 24 WHERE id = 3233;
UPDATE city_subway_station SET sort = 25 WHERE id = 3206;
UPDATE city_subway_station SET sort = 26 WHERE id = 3217;
UPDATE city_subway_station SET sort = 27 WHERE id = 3211;
UPDATE city_subway_station SET sort = 28 WHERE id = 3219;
UPDATE city_subway_station SET sort = 22 WHERE id = 3246;
UPDATE city_subway_station SET sort = 23 WHERE id = 3228;
UPDATE city_subway_station SET sort = 24 WHERE id = 3245;
UPDATE city_subway_station SET sort = 25 WHERE id = 3244;
UPDATE city_subway_station SET sort = 26 WHERE id = 3236;
UPDATE city_subway_station SET sort = 27 WHERE id = 3222;

-- 杭州地铁2号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3212;
UPDATE city_subway_station SET sort = 2 WHERE id = 3238;
UPDATE city_subway_station SET sort = 3 WHERE id = 3247;
UPDATE city_subway_station SET sort = 4 WHERE id = 3251;
UPDATE city_subway_station SET sort = 5 WHERE id = 3242;
UPDATE city_subway_station SET sort = 6 WHERE id = 3250;
UPDATE city_subway_station SET sort = 7 WHERE id = 3239;
UPDATE city_subway_station SET sort = 8 WHERE id = 3252;
UPDATE city_subway_station SET sort = 9 WHERE id = 3223;
UPDATE city_subway_station SET sort = 10 WHERE id = 3225;
UPDATE city_subway_station SET sort = 11 WHERE id = 3253;
UPDATE city_subway_station SET sort = 12 WHERE id = 3224;

-- 杭州地铁4号线站点序号更新
UPDATE city_subway_station SET sort = 1 WHERE id = 3215;
UPDATE city_subway_station SET sort = 2 WHERE id = 3199;
UPDATE city_subway_station SET sort = 3 WHERE id = 3248;
UPDATE city_subway_station SET sort = 4 WHERE id = 3235;
UPDATE city_subway_station SET sort = 5 WHERE id = 3216;
UPDATE city_subway_station SET sort = 6 WHERE id = 3213;
UPDATE city_subway_station SET sort = 7 WHERE id = 3249;
UPDATE city_subway_station SET sort = 8 WHERE id = 3243;
UPDATE city_subway_station SET sort = 9 WHERE id = 3237;
UPDATE city_subway_station SET sort = 10 WHERE id = 3221;