/**创建flat_flats、flat_flats_prototype、flat_room、flat_room_prototype历史表**/

USE mogoroomdb;

/**创建公寓历史表**/
drop table if exists flat_flats_his;
CREATE TABLE flat_flats_his (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '公寓历史表ID',
  flatsId INT(11) NOT NULL COMMENT '公寓记录ID',
  flatsNum VARCHAR(20) DEFAULT NULL COMMENT '公寓编号  市号+区编号+该区的第N套客房',
  communityId INT(11) DEFAULT NULL COMMENT '所属小区',
  districtId INT(11) DEFAULT NULL COMMENT '冗余字段：区域id',
  buildingId VARCHAR(11) DEFAULT NULL COMMENT '栋座号id',
  building VARCHAR(255) DEFAULT NULL COMMENT '楼栋号(8栋102号)',
  flatType VARCHAR(11) DEFAULT NULL COMMENT '公寓类型',
  floorNum INT(11) DEFAULT NULL COMMENT '楼层号',
  floorCountNum INT(11) DEFAULT NULL COMMENT '总楼层数',
  roomNum VARCHAR(32) DEFAULT NULL COMMENT '房间号几零几',
  bedroomCount INT(11) DEFAULT '0' COMMENT '卧室数',
  parlorCount INT(11) DEFAULT '0' COMMENT '客厅数',
  kitchenCount INT(11) DEFAULT '0' COMMENT '厨房数',
  balconyCount INT(11) DEFAULT '0' COMMENT '阳台数',
  toiletCount INT(11) DEFAULT '0' COMMENT '厕所数',
  isDuplex TINYINT(1) DEFAULT '0' COMMENT '复式0不是1是',
  oldType VARCHAR(10) DEFAULT NULL COMMENT '原始房型',
  area DECIMAL(12,2) DEFAULT NULL COMMENT '面积',
  landlordId INT(11) DEFAULT NULL COMMENT '职业房东Id',
  ownersId INT(11) DEFAULT NULL COMMENT '业主',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  createby INT(11) DEFAULT NULL COMMENT '创建人',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  status TINYINT(1) DEFAULT '1' COMMENT '状态(0无效1有效)',
  isVerify INT(11) DEFAULT '0' COMMENT '审核状态(0审核中1通过2未通过)',
  hasSmartLock TINYINT(1) DEFAULT '0' COMMENT '智能门锁(0没有1有)',
  rentType TINYINT(1) DEFAULT NULL COMMENT '出租类型(1自营2合租3整租)',
  isRemoved TINYINT(1) DEFAULT '0' COMMENT '是否有效，逻辑删除字段',
  elevatorCount INT(11) DEFAULT NULL COMMENT '电梯数',
  level INT(11) DEFAULT NULL COMMENT '房源等级(1精品房源，2、3、4是普通房源，目前录入默认会是2；1/2/3/4分别对应A/B/C/D)',
  saleManId INT(11) DEFAULT NULL COMMENT '员工ID',
  roomTypePic VARCHAR(128) DEFAULT NULL COMMENT '存放公寓的房型图片地址',
  updateBy INT(11) DEFAULT NULL COMMENT '更新人',
  createChannel INT(1) DEFAULT NULL COMMENT '数据创建来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  updateChannel INT(1) DEFAULT NULL COMMENT '数据更新来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  nickName VARCHAR(50) DEFAULT NULL COMMENT '公寓别名',
  unit VARCHAR(20) DEFAULT NULL COMMENT '单元',
  protoType INT(11) NOT NULL DEFAULT '0' COMMENT '-1：房型数据 0：不存在房型的房源 >0：存在模板的房源所对应房型的编号；',
  flatsTag INT(11) NOT NULL DEFAULT '1' COMMENT '房源类型 1：分散式，2：集中式',
  operType CHAR(1) NOT NULL COMMENT '该历史记录产生时的操作类型(A:新增 U:更新 D:删除)',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='公寓历史记录表';


/**创建公寓房型历史表**/
drop table if exists flat_flats_prototype_his;
CREATE TABLE flat_flats_prototype_his (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '公寓房型历史表ID',
  flatsTypeId INT(11) NOT NULL COMMENT '公寓房型记录ID',
  communityId INT(11) DEFAULT NULL COMMENT '所属小区',
  districtId INT(11) DEFAULT NULL COMMENT '区域id',
  buildingId VARCHAR(11) DEFAULT NULL COMMENT '栋座号id',
  building VARCHAR(255) DEFAULT NULL COMMENT '楼栋号(8栋102号)',
  flatType VARCHAR(11) DEFAULT NULL COMMENT '公寓类型',
  floorNum INT(11) DEFAULT NULL COMMENT '楼层号',
  floorCountNum INT(11) DEFAULT NULL COMMENT '总楼层数',
  bedroomCount INT(11) DEFAULT '0' COMMENT '卧室数',
  parlorCount INT(11) DEFAULT '0' COMMENT '客厅数',
  kitchenCount INT(11) DEFAULT '0' COMMENT '厨房数',
  balconyCount INT(11) DEFAULT '0' COMMENT '阳台数',
  toiletCount INT(11) DEFAULT '0' COMMENT '厕所数',
  isDuplex TINYINT(1) DEFAULT '0' COMMENT '复式0不是1是',
  oldType VARCHAR(10) DEFAULT NULL COMMENT '原始房型',
  area DECIMAL(12,2) DEFAULT NULL COMMENT '面积',
  landlordId INT(11) DEFAULT NULL COMMENT '职业房东Id',
  ownersId INT(11) DEFAULT NULL COMMENT '业主',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  createby INT(11) DEFAULT NULL COMMENT '创建人',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  status TINYINT(1) DEFAULT '1' COMMENT '状态(0无效1有效)',
  isVerify INT(11) DEFAULT '0' COMMENT '审核状态(0审核中1通过2未通过)',
  hasSmartLock TINYINT(1) DEFAULT '0' COMMENT '智能门锁(0没有1有)',
  rentType TINYINT(1) DEFAULT NULL COMMENT '出租类型(1自营2合租3整租)',
  isRemoved TINYINT(1) DEFAULT '0' COMMENT '是否有效，逻辑删除字段',
  elevatorCount INT(11) DEFAULT NULL COMMENT '电梯数',
  level INT(11) DEFAULT '0' COMMENT '预留字段房源等级',
  saleManId INT(11) DEFAULT NULL COMMENT '拓展人',
  roomTypePic VARCHAR(128) DEFAULT NULL COMMENT '存放公寓的房型图片地址',
  updateBy INT(11) DEFAULT NULL COMMENT '更新人',
  createChannel INT(1) DEFAULT NULL COMMENT '数据创建来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  updateChannel INT(1) DEFAULT NULL COMMENT '数据更新来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  nickName VARCHAR(50) DEFAULT NULL COMMENT '公寓别名',
  unit VARCHAR(20) DEFAULT NULL COMMENT '单元',
  flatsTag INT(11) NOT NULL DEFAULT '1' COMMENT '房源类型 1：分散式，2：集中式',
  operType CHAR(1) NOT NULL COMMENT '该历史记录产生时的操作类型(A:新增 U:更新 D:删除)',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='公寓房型历史表';

/**创建房间历史表**/
drop table if exists flat_room_his;
CREATE TABLE flat_room_his (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '房间历史表ID',
  roomId INT(11) NOT NULL COMMENT '房间id',  
  flatsId INT(11) NOT NULL DEFAULT '0' COMMENT '公寓ID',
  styleCode VARCHAR(16) DEFAULT NULL COMMENT '风格引用-字典表(style)',
  communityId INT(11) NOT NULL DEFAULT '0' COMMENT '冗余字段：小区id',
  districtId INT(11) NOT NULL DEFAULT '0' COMMENT '冗余字段：区域id',
  renterId INT(11) DEFAULT NULL COMMENT '当前入住人id',
  roomNum VARCHAR(20) DEFAULT NULL COMMENT '房间编号',
  roomName VARCHAR(30) NOT NULL DEFAULT '' COMMENT '房间名称',
  subTitle VARCHAR(50) NOT NULL DEFAULT '' COMMENT '房间副标题',
  bookingPrice DECIMAL(12,2) DEFAULT NULL COMMENT '预定价格',
  roomPrice DECIMAL(12,2) DEFAULT NULL COMMENT '房间价格',
  salePrice DECIMAL(12,2) DEFAULT NULL COMMENT '销售价格',
  area DECIMAL(12,2) NOT NULL COMMENT '面积',
  payType VARCHAR(255) NOT NULL DEFAULT '1' COMMENT '付款类型:付三押一(1),付一押一(2),付六押一(3),付十二押一(4);',
  person INT(1) DEFAULT '0' COMMENT '人数',
  face VARCHAR(10) NOT NULL DEFAULT '' COMMENT '朝向',
  roomType TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1.房间，2.公共区域',
  rentStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '出租状态：1未出租,2已出租,3已预定,4未上线',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  intro VARCHAR(500) DEFAULT NULL COMMENT '介绍',
  updateTime DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  status TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否有效（0无效1有效）',
  claim VARCHAR(255) DEFAULT NULL COMMENT '住房要求',
  smartLock TINYINT(1) NOT NULL DEFAULT '0' COMMENT '智能门锁',
  createby INT(11) DEFAULT NULL COMMENT '创建人',
  lockTime DATETIME NULL DEFAULT NULL COMMENT '房间锁定时间',
  lockBy INT(11) DEFAULT '0' COMMENT '锁房间人的id',
  signedOrderId INT(11) DEFAULT NULL COMMENT '签约单ID',
  payType2 VARCHAR(128) DEFAULT '0' COMMENT '付款方式二。0:默认，不代表任何付款方式付款类型:付一押一(2),付一押一蘑菇宝(9)',
  salePrice2 INT(11) DEFAULT NULL COMMENT '付款方式二 销售价格',
  picDescribe VARCHAR(500) DEFAULT NULL COMMENT '公寓图片描述',
  roomPrice2 INT(11) DEFAULT NULL COMMENT '付款方式二 房屋价格',
  updateBy INT(11) DEFAULT NULL COMMENT '更新人',
  createChannel INT(1) DEFAULT NULL COMMENT '数据创建来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  updateChannel INT(1) DEFAULT NULL COMMENT '数据更新来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  isPutaway INT(1) DEFAULT '0' COMMENT '是否上架(0:下架，1：上架)',
  putawayTime DATETIME DEFAULT '2015-10-01 00:00:00' COMMENT '上架时间',
  checkInTime DATETIME DEFAULT NULL COMMENT '可入住时间',
  agencyFee DECIMAL(10,2) DEFAULT NULL COMMENT '中介费',
  manageFee DECIMAL(10,2) DEFAULT NULL COMMENT '管理费',
  roomScore DECIMAL(12,2) DEFAULT NULL COMMENT '房间分数',
  protoType INT(11) NOT NULL DEFAULT '0' COMMENT '-1：房型数据 0：不存在房型的房源 >0：存在模板的房源所对应房型的编号；',
  showPrice DECIMAL(12,2) DEFAULT '0.00' COMMENT '列表显示价格',
  onlineStatus TINYINT(4) NOT NULL DEFAULT '2' COMMENT '上架下架状态。参考字段表的RoomOnlineStatus groupName。',
  verifyStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '审核状态。参考字段表的RoomVerifyStatus groupName。',
  availableStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '房间占用状态。参考字段表的RoomAvailableStatus groupName。',
  statusUpdateTime DATETIME DEFAULT NULL COMMENT '房态更新时间',
  availableEndTime DATETIME DEFAULT NULL COMMENT '房间占用状态的有效截止时间',
  operType CHAR(1) NOT NULL COMMENT '该历史记录产生时的操作类型(A:新增 U:更新 D:删除)',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='房间信息历史表';

/**创建房间房型历史表**/
drop table if exists flat_room_prototype_his;
CREATE TABLE flat_room_prototype_his (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  roomProtoTypeId INT(11) NOT NULL COMMENT '房间房型ID', 
  flatsId INT(11) NOT NULL DEFAULT '0' COMMENT '公寓ID',
  styleCode VARCHAR(16) DEFAULT NULL COMMENT '风格引用-字典表(style)',
  communityId INT(11) NOT NULL DEFAULT '0' COMMENT '冗余字段：小区id',
  districtId INT(11) NOT NULL DEFAULT '0' COMMENT '冗余字段：区域id',
  renterId INT(11) DEFAULT NULL COMMENT '当前入住人id',
  roomName VARCHAR(30) NOT NULL DEFAULT '' COMMENT '房间名称',
  subTitle VARCHAR(50) NOT NULL DEFAULT '' COMMENT '房间副标题',
  bookingPrice DECIMAL(12,2) DEFAULT NULL COMMENT '面积',
  roomPrice DECIMAL(12,2) DEFAULT NULL COMMENT '房间价格',
  salePrice DECIMAL(12,2) DEFAULT NULL COMMENT '销售价格',
  area DECIMAL(12,2) DEFAULT NULL COMMENT '面积',
  payType VARCHAR(255) NOT NULL DEFAULT '1' COMMENT '付款类型:付三押一(1),付一押一(2),付六押一(3),付十二押一(4);',
  person INT(1) DEFAULT '0' COMMENT '人数',
  face VARCHAR(10) NOT NULL DEFAULT '' COMMENT '朝向',
  roomType TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1.房间，2.公共区域',
  rentStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '出租状态：1未出租,2已出租,3已预定,4未上线',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  intro VARCHAR(255) DEFAULT NULL COMMENT '介绍',
  updateTime DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  status TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否有效（0无效1有效）',
  claim VARCHAR(255) DEFAULT NULL COMMENT '住房要求',
  smartLock TINYINT(1) NOT NULL DEFAULT '0' COMMENT '智能门锁',
  createby INT(11) DEFAULT NULL COMMENT '创建人',
  lockTime DATETIME NULL DEFAULT NULL COMMENT '房间锁定时间',
  lockBy INT(11) DEFAULT '0' COMMENT '锁房间人的id',
  payType2 VARCHAR(128) DEFAULT '0' COMMENT '付款方式二。0:默认，不代表任何付款方式付款类型:付一押一(2),付一押一蘑菇宝(9)',
  salePrice2 INT(11) DEFAULT NULL COMMENT '付款方式二 销售价格',
  picDescribe VARCHAR(500) DEFAULT NULL COMMENT '公寓图片描述',
  roomPrice2 INT(11) DEFAULT NULL COMMENT '付款方式二 房屋价格',
  updateBy INT(11) DEFAULT NULL COMMENT '更新人',
  createChannel INT(1) DEFAULT NULL COMMENT '数据创建来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  updateChannel INT(1) DEFAULT NULL COMMENT '数据更新来源(1:租客APP,2:BS后台,3:官网,4:房东APP,5:房东PC)',
  isPutaway INT(1) DEFAULT '0' COMMENT '是否上架(0:下架，1：上架)',
  putawayTime DATETIME DEFAULT '2015-10-01 00:00:00' COMMENT '上架时间',
  checkInTime DATETIME DEFAULT NULL COMMENT '可入住时间',
  agencyFee DECIMAL(10,2) DEFAULT NULL COMMENT '中介费',
  manageFee DECIMAL(10,2) DEFAULT NULL COMMENT '管理费',
  roomScore DECIMAL(12,2) DEFAULT NULL COMMENT '房间分数',
  operType CHAR(1) NOT NULL COMMENT '该历史记录产生时的操作类型(A:新增 U:更新 D:删除)',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='房间房型历史表';
